<?php

use Illuminate\Database\Seeder;
use App\Cadena;
use App\User;
use App\Tienda;
use Faker\Factory;
use App\Producto;

class CadenasTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        User::create([
            'name' => 'Edgar Huaranga',
            'email' => 'edhu1227@gmail.com',
            'password' => Hash::make('huaranga14'),
        ]);

        Cadena::create(['nombre'=>'Saga']);
        Cadena::create(['nombre'=>'Ripley']);
        Cadena::create(['nombre'=>'Paris']);
        Cadena::create(['nombre'=>'Tottus']);
        Cadena::create(['nombre'=>'Stylos']);
        Cadena::create(['nombre'=>'Oeschle']);

        Tienda::create(['cadena_id'=>'6', 'nombre_sede'=>' PRIMAVERA','direccion'=>'AV.AVIACION ESQ. CON PRIMAVERA S/N','ubigeo'=>'150101']);
        Tienda::create(['cadena_id'=>'6', 'nombre_sede'=>' CENTRO CÍVICO','direccion'=>'AV. INCA GARCILASO DE LA VEGA 1337','ubigeo'=>'150101']);
        Tienda::create(['cadena_id'=>'6', 'nombre_sede'=>' SALAVERRY','direccion'=>'AV.FELIPE SANTIAGO SALAVERRY CDRA.24 ','ubigeo'=>'150101']);
        Tienda::create(['cadena_id'=>'6', 'nombre_sede'=>' JIRÓN DE LA UNIÓN','direccion'=>'JIRÓN DE LA UNIÓN 600','ubigeo'=>'150101']);
        Tienda::create(['cadena_id'=>'6', 'nombre_sede'=>' JOCKEY PLAZA','direccion'=>'AV. JAVIER PRADO ESTE 4200 ','ubigeo'=>'150101']);
        Tienda::create(['cadena_id'=>'6', 'nombre_sede'=>' PLAZA LIMA NORTE','direccion'=>'AV.ALFREDO MENDIOLA 1400','ubigeo'=>'150101']);
        Tienda::create(['cadena_id'=>'6', 'nombre_sede'=>' SAN BORJA','direccion'=>'JR. VITTORE SCARPAZZA C. 241 ','ubigeo'=>'150101']);
        Tienda::create(['cadena_id'=>'6', 'nombre_sede'=>' MIRAFLORES','direccion'=>'PJE. LOS PINOS 140 ','ubigeo'=>'150101']);
        Tienda::create(['cadena_id'=>'6', 'nombre_sede'=>'MALL SUR','direccion'=>'AV LOS LIRIOS 301 ','ubigeo'=>'150101']);
        Tienda::create(['cadena_id'=>'6', 'nombre_sede'=>'LA CURVA','direccion'=>'CALLE 1RO DE MAYO S/N PUEBLO JOVEN ','ubigeo'=>'150101']);
        Tienda::create(['cadena_id'=>'1', 'nombre_sede'=>' SALAVERRY','direccion'=>'AV. GRAL. SALAVERRY 2370','ubigeo'=>'150101']);
        Tienda::create(['cadena_id'=>'1', 'nombre_sede'=>' JOCKEY PLAZA','direccion'=>'AV. JAVIER PRADO ESTE 4200','ubigeo'=>'150101']);
        Tienda::create(['cadena_id'=>'1', 'nombre_sede'=>' MIRAFLORES','direccion'=>'AV. AREQUIPA 5280','ubigeo'=>'150101']);
        Tienda::create(['cadena_id'=>'1', 'nombre_sede'=>' SAN ISIDRO','direccion'=>'AV. PASEO DE LA REPÚBLICA 3220','ubigeo'=>'150101']);
        Tienda::create(['cadena_id'=>'1', 'nombre_sede'=>' CENTRO CÍVICO','direccion'=>'AV INCA GARCILASO DE LA VEGA 1337','ubigeo'=>'150101']);
        Tienda::create(['cadena_id'=>'1', 'nombre_sede'=>' SAN MIGUEL','direccion'=>'AV. DE LA MARINA 2100','ubigeo'=>'150101']);
        Tienda::create(['cadena_id'=>'1', 'nombre_sede'=>' MEGAPLAZA','direccion'=>'AV INDUSTRIAL 3515','ubigeo'=>'150101']);
        Tienda::create(['cadena_id'=>'1', 'nombre_sede'=>' SANTA ANITA','direccion'=>'CARR. CENTRAL 111','ubigeo'=>'150101']);
        Tienda::create(['cadena_id'=>'1', 'nombre_sede'=>' LIMA NORTE','direccion'=>'CENTRO COMERCIAL PLAZA NORTE, AV. TOMAS VALLE','ubigeo'=>'150101']);
        Tienda::create(['cadena_id'=>'1', 'nombre_sede'=>' MALL DEL SUR','direccion'=>'AV LOS LIRIOS 301 ','ubigeo'=>'150101']);
        Tienda::create(['cadena_id'=>'1', 'nombre_sede'=>' ANGAMOS','direccion'=>'AV. ANGAMOS 1803','ubigeo'=>'150101']);
        Tienda::create(['cadena_id'=>'1', 'nombre_sede'=>'BELLAVISTA','direccion'=>'AV. OSCAR R. BENAVIDES 3866','ubigeo'=>'150101']);
        Tienda::create(['cadena_id'=>'1', 'nombre_sede'=>' JIRÓN DE LA UNIÓN','direccion'=>'JIRÓN DE LA UNIÓN 517','ubigeo'=>'150101']);


        Producto::create(['sku_cic'=>'2112030101','sku'=>'13206236','cadena_id'=>'SAGA','nombre'=>'Colchon Technodream Breeze 1.0 PLZ','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'Colchon Technodream Breeze 1.0 PLZ','precio'=>'699','UNIDAD'=>'UND']);
        Producto::create(['sku_cic'=>'2114030101','sku'=>'13206237','cadena_id'=>'SAGA','nombre'=>'Colchon Technodream Breeze 1.5 PLZ','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'Colchon Technodream Breeze 1.5 PLZ','precio'=>'699','UNIDAD'=>'UND']);
        Producto::create(['sku_cic'=>'2115030101','sku'=>'13206238','cadena_id'=>'SAGA','nombre'=>'Colchon Technodream Breeze 2.0 PLZ','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'Colchon Technodream Breeze 2.0 PLZ','precio'=>'859','UNIDAD'=>'UND']);
        Producto::create(['sku_cic'=>'2112030601','sku'=>'16374359','cadena_id'=>'SAGA','nombre'=>'Colchon Technodream Ozono 1.0 plz','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'Colchon Technodream Ozono 1.0 plz','precio'=>'1099','UNIDAD'=>'UND']);
        Producto::create(['sku_cic'=>'2114030601','sku'=>'13206239','cadena_id'=>'SAGA','nombre'=>'Colchon Technodream Ozono 1.5 plz','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'Colchon Technodream Ozono 1.5 plz','precio'=>'1099','UNIDAD'=>'UND']);
        Producto::create(['sku_cic'=>'2115030601','sku'=>'13206241','cadena_id'=>'SAGA','nombre'=>'Colchon Technodream Ozono 2.0 PLZ','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'Colchon Technodream Ozono 2.0 PLZ','precio'=>'1179','UNIDAD'=>'UND']);
        Producto::create(['sku_cic'=>'2116030601','sku'=>'13206242','cadena_id'=>'SAGA','nombre'=>'Colchon Technodream Ozono Queen','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'Colchon Technodream Ozono Queen','precio'=>'1599','UNIDAD'=>'UND']);
        Producto::create(['sku_cic'=>'2117030601','sku'=>'13206243','cadena_id'=>'SAGA','nombre'=>'Colchon Technodream Ozono King','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'Colchon Technodream Ozono King','precio'=>'1899','UNIDAD'=>'UND']);
        Producto::create(['sku_cic'=>'1114031001','sku'=>'16043983','cadena_id'=>'SAGA','nombre'=>'Cama Americana Xeon 1.5 plz','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'Cama Americana Xeon 1.5 plz','precio'=>'919','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1115031001','sku'=>'16043999','cadena_id'=>'SAGA','nombre'=>'Cama Americana Xeon 2.0 plz','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'Cama Americana Xeon 2.0 plz','precio'=>'1129','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1394000201','sku'=>'16044000','cadena_id'=>'SAGA','nombre'=>'Kit Americano Xeon 1.5 plz','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'Kit Americano Xeon 1.5 plz','precio'=>'1129','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1395000201','sku'=>'16044001','cadena_id'=>'SAGA','nombre'=>'Kit Americano Xeon 2.0 plz','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'Kit Americano Xeon 2.0 plz','precio'=>'1329','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'2114030201','sku'=>'16374362','cadena_id'=>'SAGA','nombre'=>'Colchon Technodream Cool  1.0 plz','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'Colchon Technodream Cool  1.0 plz','precio'=>'779','UNIDAD'=>'UND']);
        Producto::create(['sku_cic'=>'2114030201','sku'=>'13889635','cadena_id'=>'SAGA','nombre'=>'Colchon Technodream Cool  1.5 plz','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'Colchon Technodream Cool  1.5 plz','precio'=>'779','UNIDAD'=>'UND']);
        Producto::create(['sku_cic'=>'2115030201','sku'=>'13889646','cadena_id'=>'SAGA','nombre'=>'Colchon Technodream Cool 2.0 plz','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'Colchon Technodream Cool 2.0 plz','precio'=>'999','UNIDAD'=>'UND']);
        Producto::create(['sku_cic'=>'2116030201','sku'=>'13889647','cadena_id'=>'SAGA','nombre'=>'Colchon Technodream Cool Queen','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'Colchon Technodream Cool Queen','precio'=>'1499','UNIDAD'=>'UND']);
        Producto::create(['sku_cic'=>'2112030301','sku'=>'13288120','cadena_id'=>'SAGA','nombre'=>'Colchon Technodream Energy 1.0 plz','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'Colchon Technodream Energy 1.0 plz','precio'=>'849','UNIDAD'=>'UND']);
        Producto::create(['sku_cic'=>'2114030301','sku'=>'13288121','cadena_id'=>'SAGA','nombre'=>'Colchon Technodream Energy 1.5 pz','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'Colchon Technodream Energy 1.5 pz','precio'=>'879','UNIDAD'=>'UND']);
        Producto::create(['sku_cic'=>'2115030301','sku'=>'13288125','cadena_id'=>'SAGA','nombre'=>'Colchon Technodream Energy 2.0 plz','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'Colchon Technodream Energy 2.0 plz','precio'=>'1099','UNIDAD'=>'UND']);
        Producto::create(['sku_cic'=>'2116030301','sku'=>'13288126','cadena_id'=>'SAGA','nombre'=>'Colchon Technodream Energy Queen','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'Colchon Technodream Energy Queen','precio'=>'1449','UNIDAD'=>'UND']);
        Producto::create(['sku_cic'=>'2117030301','sku'=>'13288128','cadena_id'=>'SAGA','nombre'=>'Colchon Technodream Energy King','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'Colchon Technodream Energy King','precio'=>'1799','UNIDAD'=>'UND']);
        Producto::create(['sku_cic'=>'2124030401','sku'=>'13889648','cadena_id'=>'SAGA','nombre'=>'Colchon Technodream Gravity 1.5 plz','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'Colchon Technodream Gravity 1.5 plz','precio'=>'1099','UNIDAD'=>'UND']);
        Producto::create(['sku_cic'=>'2125030401','sku'=>'13889742','cadena_id'=>'SAGA','nombre'=>'Colchon Technodream Gravity 2.0 plz','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'Colchon Technodream Gravity 2.0 plz','precio'=>'1199','UNIDAD'=>'UND']);
        Producto::create(['sku_cic'=>'2126030401','sku'=>'13889743','cadena_id'=>'SAGA','nombre'=>'Colchon Technodream Gravity Queen','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'Colchon Technodream Gravity Queen','precio'=>'1599','UNIDAD'=>'UND']);
        Producto::create(['sku_cic'=>'2127030401','sku'=>'13889744','cadena_id'=>'SAGA','nombre'=>'Colchon Technodream Gravity King','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'Colchon Technodream Gravity King','precio'=>'2099','UNIDAD'=>'UND']);
        Producto::create(['sku_cic'=>'1112030101','sku'=>'13206691','cadena_id'=>'SAGA','nombre'=>'CAMA AMERICANA TECHNODREAM BREEZE 1.0 PLZ','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'CAMA AMERICANA TECHNODREAM BREEZE 1.0 PLZ','precio'=>'1199','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1114030101','sku'=>'13206697','cadena_id'=>'SAGA','nombre'=>'CAMA AMERICANA TECHNODREAM BREEZE 1.5 PLZ','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'CAMA AMERICANA TECHNODREAM BREEZE 1.5 PLZ','precio'=>'1299','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1115030101','sku'=>'13206701','cadena_id'=>'SAGA','nombre'=>'CAMA AMERICANA TECHNODREAM BREEZE 2.0 PLZ','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'CAMA AMERICANA TECHNODREAM BREEZE 2.0 PLZ','precio'=>'1449','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1114030601','sku'=>'16374360','cadena_id'=>'SAGA','nombre'=>'CAMA AMERICANA TECHNODREAM OZONO 1.0 PLZ','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'CAMA AMERICANA TECHNODREAM OZONO 1.0 PLZ','precio'=>'1599','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1114030601','sku'=>'13206702','cadena_id'=>'SAGA','nombre'=>'CAMA AMERICANA TECHNODREAM OZONO 1.5 PLZ','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'CAMA AMERICANA TECHNODREAM OZONO 1.5 PLZ','precio'=>'1599','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1115030601','sku'=>'13206703','cadena_id'=>'SAGA','nombre'=>'CAMA AMERICANA TECHNODREAM OZONO 2.0 PZ','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'CAMA AMERICANA TECHNODREAM OZONO 2.0 PZ','precio'=>'1799','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1116030601','sku'=>'13206811','cadena_id'=>'SAGA','nombre'=>'CAMA AMERICANA TECHNODREAM OZONO QUEEN','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'CAMA AMERICANA TECHNODREAM OZONO QUEEN','precio'=>'2599','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1117030601','sku'=>'13206812','cadena_id'=>'SAGA','nombre'=>'CAMA AMERICANA TECHNODREAM OZONO KING','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'CAMA AMERICANA TECHNODREAM OZONO KING','precio'=>'3199','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1114030201','sku'=>'16374361','cadena_id'=>'SAGA','nombre'=>'CAMA AMERICANA TECHNODREAM COOL 1.0 PLZ','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'CAMA AMERICANA TECHNODREAM COOL 1.0 PLZ','precio'=>'1449','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1114030201','sku'=>'13889745','cadena_id'=>'SAGA','nombre'=>'CAMA AMERICANA TECHNODREAM COOL 1.5 PLZ','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'CAMA AMERICANA TECHNODREAM COOL 1.5 PLZ','precio'=>'1449','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1115030201','sku'=>'13889748','cadena_id'=>'SAGA','nombre'=>'CAMA AMERICANA TECHNODREAM COOL 2.0 PLZ','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'CAMA AMERICANA TECHNODREAM COOL 2.0 PLZ','precio'=>'1799','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1116030201','sku'=>'13889749','cadena_id'=>'SAGA','nombre'=>'CAMA AMERICANA TECHNODREAM COOL QUEEN','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'CAMA AMERICANA TECHNODREAM COOL QUEEN','precio'=>'2399','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1112030301','sku'=>'13288152','cadena_id'=>'SAGA','nombre'=>'CAMA AMERICANA TECHNODREAM ENERGY 1.0 PLZ','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'CAMA AMERICANA TECHNODREAM ENERGY 1.0 PLZ','precio'=>'1549','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1114030301','sku'=>'13288153','cadena_id'=>'SAGA','nombre'=>'CAMA AMERICANA TECHNODREAM ENERGY 1.5 PLZ','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'CAMA AMERICANA TECHNODREAM ENERGY 1.5 PLZ','precio'=>'1549','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1115030301','sku'=>'13288154','cadena_id'=>'SAGA','nombre'=>'CAMA AMERICANA TECHNODREAM ENERGY 2.0 PLZ','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'CAMA AMERICANA TECHNODREAM ENERGY 2.0 PLZ','precio'=>'1849','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1116030301','sku'=>'13288161','cadena_id'=>'SAGA','nombre'=>'CAMA AMERICANA TECHNODREAM ENERGY QUEEN','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'CAMA AMERICANA TECHNODREAM ENERGY QUEEN','precio'=>'2399','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1117030301','sku'=>'13288178','cadena_id'=>'SAGA','nombre'=>'CAMA AMERICANA TECHNODREAM ENERGY KING','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'CAMA AMERICANA TECHNODREAM ENERGY KING','precio'=>'2899','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1114030401','sku'=>'13889750','cadena_id'=>'SAGA','nombre'=>'CAMA AMERICANA TECHNODREAM GRAVITY 1.5','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'CAMA AMERICANA TECHNODREAM GRAVITY 1.5','precio'=>'1599','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1115030401','sku'=>'13889751','cadena_id'=>'SAGA','nombre'=>'CAMA AMERICANA TECHNODREAM GRAVITY 2.0 plz','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'CAMA AMERICANA TECHNODREAM GRAVITY 2.0 plz','precio'=>'1899','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1116030401','sku'=>'13889752','cadena_id'=>'SAGA','nombre'=>'CAMA AMERICANA TECHNODREAM GRAVITY Quee','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'CAMA AMERICANA TECHNODREAM GRAVITY Quee','precio'=>'2599','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1117030401','sku'=>'13889753','cadena_id'=>'SAGA','nombre'=>'CAMA AMERICANA TECHNODREAM GRAVITY KING','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'CAMA AMERICANA TECHNODREAM GRAVITY KING','precio'=>'3199','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1114031401','sku'=>'16415509','cadena_id'=>'SAGA','nombre'=>'CAMA AMERICANA TECHNODREAM POCKET OXYGEN 1.5 PLZ','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'CAMA AMERICANA TECHNODREAM POCKET OXYGEN 1.5 PLZ','precio'=>'1299','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1115031401','sku'=>'16415510','cadena_id'=>'SAGA','nombre'=>'CAMA AMERICANA TECHNODREAM POCKET OXYGEN 2.0 PLZ','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'CAMA AMERICANA TECHNODREAM POCKET OXYGEN 2.0 PLZ','precio'=>'1499','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1116031401','sku'=>'16415511','cadena_id'=>'SAGA','nombre'=>'CAMA AMERICANA TECHNODREAM POCKET OXYGEN QUEEN PLZ','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'CAMA AMERICANA TECHNODREAM POCKET OXYGEN QUEEN PLZ','precio'=>'1899','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1314007201','sku'=>'16457816','cadena_id'=>'SAGA','nombre'=>'KIT AMER BLACK POCKET OXYGEN 1.5 PL','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'KIT AMER BLACK POCKET OXYGEN 1.5 PL','precio'=>'1499','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1315007201','sku'=>'16457817','cadena_id'=>'SAGA','nombre'=>'KIT AMER  BLACK POCKET OXYGEN 2 PLZ','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'KIT AMER  BLACK POCKET OXYGEN 2 PLZ','precio'=>'1899','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1316007201','sku'=>'16457818','cadena_id'=>'SAGA','nombre'=>'KIT AMER BLACK POCKET OXYGEN QS','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'KIT AMER BLACK POCKET OXYGEN QS','precio'=>'2299','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1314003202','sku'=>'14631724','cadena_id'=>'SAGA','nombre'=>'DORMITORIO NICOLE TECHNODREAM COOL 1.5','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'DORMITORIO NICOLE TECHNODREAM COOL 1.5','precio'=>'1919','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1315003202','sku'=>'14631725','cadena_id'=>'SAGA','nombre'=>'DORMITORIO NICOLE TECHNODREAM COOL 2.0','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'DORMITORIO NICOLE TECHNODREAM COOL 2.0','precio'=>'2519','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1336003101','sku'=>'14631726','cadena_id'=>'SAGA','nombre'=>'DORMITORIO NICOLE TECHNODREAM COOL Q','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'DORMITORIO NICOLE TECHNODREAM COOL Q','precio'=>'2939','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1314003402','sku'=>'14631727','cadena_id'=>'SAGA','nombre'=>'DORMITORIO NICOLE TECHNODREAM OZONO 1.5','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'DORMITORIO NICOLE TECHNODREAM OZONO 1.5','precio'=>'2149','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1315003402','sku'=>'14631728','cadena_id'=>'SAGA','nombre'=>'DORMITORIO NICOLE TECHNODREAM OZONO 2.0','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'DORMITORIO NICOLE TECHNODREAM OZONO 2.0','precio'=>'2729','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1316003402','sku'=>'14631729','cadena_id'=>'SAGA','nombre'=>'DORMITORIO NICOLE TECHNODREAM OZONO Q','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'DORMITORIO NICOLE TECHNODREAM OZONO Q','precio'=>'3149','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1314003302','sku'=>'14631730','cadena_id'=>'SAGA','nombre'=>'DORMITORIO NICOLE TECHNODREAM GRAVITY 1.5','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'DORMITORIO NICOLE TECHNODREAM GRAVITY 1.5','precio'=>'2049','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1315003302','sku'=>'14631731','cadena_id'=>'SAGA','nombre'=>'DORMITORIO NICOLE TECHNODREAM GRAVITY 2.0','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'DORMITORIO NICOLE TECHNODREAM GRAVITY 2.0','precio'=>'2589','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1316003302','sku'=>'14631732','cadena_id'=>'SAGA','nombre'=>'DORMITORIO NICOLE TECHNODREAM GRAVITY Q','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'DORMITORIO NICOLE TECHNODREAM GRAVITY Q','precio'=>'2919','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1315001301','sku'=>'13953983','cadena_id'=>'SAGA','nombre'=>'DORMITORIO CANTABRIA CAJONES OZONO 2.0','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'DORMITORIO CANTABRIA CAJONES OZONO 2.0','precio'=>'3379','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1316001301','sku'=>'13953984','cadena_id'=>'SAGA','nombre'=>'DORMITORIO CANTABRIA CAJONES OZONO Q','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'DORMITORIO CANTABRIA CAJONES OZONO Q','precio'=>'3999','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1315002701','sku'=>'14631709','cadena_id'=>'SAGA','nombre'=>'DORMITORIO KAELA CAJONES OZONO 2.0 ','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'DORMITORIO KAELA CAJONES OZONO 2.0 ','precio'=>'3329','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1316002701','sku'=>'14631710','cadena_id'=>'SAGA','nombre'=>'DORMITORIO KAELA CAJONES OZONO Q','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'DORMITORIO KAELA CAJONES OZONO Q','precio'=>'3949','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1315005501','sku'=>'14631713','cadena_id'=>'SAGA','nombre'=>'DORMITORIO SOFIA  CAJONES OZONO 2.0','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'DORMITORIO SOFIA  CAJONES OZONO 2.0','precio'=>'3329','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1316005501','sku'=>'14631714','cadena_id'=>'SAGA','nombre'=>'DORMITORIO SOFIA  CAJONES OZONO Q','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'DORMITORIO SOFIA  CAJONES OZONO Q','precio'=>'3949','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1315003901','sku'=>'13953985','cadena_id'=>'SAGA','nombre'=>'DORMITORIO OPORTO CAJONES OZONO 2.0','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'DORMITORIO OPORTO CAJONES OZONO 2.0','precio'=>'3379','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1316003901','sku'=>'13953986','cadena_id'=>'SAGA','nombre'=>'DORMITORIO OPORTO CAJONES OZONO Q','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'DORMITORIO OPORTO CAJONES OZONO Q','precio'=>'3999','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1315001101','sku'=>'14631736','cadena_id'=>'SAGA','nombre'=>'DORMITORIO CANTABRIA CAJONES GRAVITY 20','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'DORMITORIO CANTABRIA CAJONES GRAVITY 20','precio'=>'3239','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1316001101','sku'=>'14631737','cadena_id'=>'SAGA','nombre'=>'DORMITORIO CANTABRIA CAJONES GRAVITY Q','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'DORMITORIO CANTABRIA CAJONES GRAVITY Q','precio'=>'3769','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1315002501','sku'=>'14631711','cadena_id'=>'SAGA','nombre'=>'DORMITORIO KAELA CAJONES GRAVITY 2.0','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'DORMITORIO KAELA CAJONES GRAVITY 2.0','precio'=>'3339','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1316002501','sku'=>'14631712','cadena_id'=>'SAGA','nombre'=>'DORMITORIO KAELA CAJONES GRAVITY Q','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'DORMITORIO KAELA CAJONES GRAVITY Q','precio'=>'3719','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1315005301','sku'=>'14631715','cadena_id'=>'SAGA','nombre'=>'DORMITORIO SOFIA  CAJONES GRAVITY 2.0','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'DORMITORIO SOFIA  CAJONES GRAVITY 2.0','precio'=>'3339','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1316005301','sku'=>'14631716','cadena_id'=>'SAGA','nombre'=>'DORMITORIO SOFIA  CAJONES GRAVITY Q','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'DORMITORIO SOFIA  CAJONES GRAVITY Q','precio'=>'3719','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1315003701','sku'=>'14631744','cadena_id'=>'SAGA','nombre'=>'DORMITORIO OPORTO CAJONES GRAVITY 2.0','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'DORMITORIO OPORTO CAJONES GRAVITY 2.0','precio'=>'3239','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1316003701','sku'=>'14631745','cadena_id'=>'SAGA','nombre'=>'DORMITORIO OPORTO CAJONES GRAVITY Q','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'DORMITORIO OPORTO CAJONES GRAVITY Q','precio'=>'3769','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1315002201','sku'=>'15868328','cadena_id'=>'SAGA','nombre'=>'DORMITORIO DiAGONAL OZONO 2.0','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'DORMITORIO DiAGONAL OZONO 2.0','precio'=>'3429','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1316002201','sku'=>'15868329','cadena_id'=>'SAGA','nombre'=>'DORMITORIO DiAGONAL OZONO Q','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'DORMITORIO DiAGONAL OZONO Q','precio'=>'4049','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1317002201','sku'=>'15868330','cadena_id'=>'SAGA','nombre'=>'DORMITORIO DiAGONAL OZONO K','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'DORMITORIO DiAGONAL OZONO K','precio'=>'4839','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1315001801','sku'=>'15868331','cadena_id'=>'SAGA','nombre'=>'DORMITORIO DiAGONAL GRAVITY 2.0','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'DORMITORIO DiAGONAL GRAVITY 2.0','precio'=>'3299','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1316001801','sku'=>'15868332','cadena_id'=>'SAGA','nombre'=>'DORMITORIO DiAGONAL GRAVITY Q','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'DORMITORIO DiAGONAL GRAVITY Q','precio'=>'3799','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1317001801','sku'=>'15868333','cadena_id'=>'SAGA','nombre'=>'DORMITORIO DiAGONAL GRAVITY K','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'DORMITORIO DiAGONAL GRAVITY K','precio'=>'4649','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1315001501','sku'=>'15868340','cadena_id'=>'SAGA','nombre'=>'DORMITORIO FACUNDO OZONO 2.0','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'DORMITORIO FACUNDO OZONO 2.0','precio'=>'3359','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1316001501','sku'=>'15868341','cadena_id'=>'SAGA','nombre'=>'DORMITORIO FACUNDO OZONO Q','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'DORMITORIO FACUNDO OZONO Q','precio'=>'3979','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1317001501','sku'=>'15868342','cadena_id'=>'SAGA','nombre'=>'DORMITORIO FACUNDO OZONO K','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'DORMITORIO FACUNDO OZONO K','precio'=>'4769','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1315000401','sku'=>'15868343','cadena_id'=>'SAGA','nombre'=>'DORMITORIO FACUNDO GRAVITY 20','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'DORMITORIO FACUNDO GRAVITY 20','precio'=>'3239','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1316000401','sku'=>'15868344','cadena_id'=>'SAGA','nombre'=>'DORMITORIO FACUNDO GRAVITY Q','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'DORMITORIO FACUNDO GRAVITY Q','precio'=>'3769','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1317000401','sku'=>'15868345','cadena_id'=>'SAGA','nombre'=>'DORMITORIO FACUNDO GRAVITY K','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'DORMITORIO FACUNDO GRAVITY K','precio'=>'4549','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1324001601','sku'=>'13889759','cadena_id'=>'SAGA','nombre'=>'CAMA DIVAN LAQUEADA TECHNODREAM COOL 1.5','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'CAMA DIVAN LAQUEADA TECHNODREAM COOL 1.5','precio'=>'2069','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1325001601','sku'=>'13889763','cadena_id'=>'SAGA','nombre'=>'CAMA DIVAN LAQUEADA TECHNODREAM COOL 2.0','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'CAMA DIVAN LAQUEADA TECHNODREAM COOL 2.0','precio'=>'2619','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1326001601','sku'=>'13889764','cadena_id'=>'SAGA','nombre'=>'CAMA DIVAN LAQUEADA TECHNODREAM COOL Q','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'CAMA DIVAN LAQUEADA TECHNODREAM COOL Q','precio'=>'3139','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1324001901','sku'=>'13646571','cadena_id'=>'SAGA','nombre'=>'CAMA DIVAN LAQUEADA TECHNODREAM OZONO 1.5','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'CAMA DIVAN LAQUEADA TECHNODREAM OZONO 1.5','precio'=>'2249','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1325001901','sku'=>'13646573','cadena_id'=>'SAGA','nombre'=>'CAMA DIVAN LAQUEADA TECHNODREAM OZONO 2.0','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'CAMA DIVAN LAQUEADA TECHNODREAM OZONO 2.0','precio'=>'2779','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1326001901','sku'=>'13646574','cadena_id'=>'SAGA','nombre'=>'CAMA DIVAN LAQUEADA TECHNODREAM OZONO Q','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'CAMA DIVAN LAQUEADA TECHNODREAM OZONO Q','precio'=>'3349','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1324001701','sku'=>'14631748','cadena_id'=>'SAGA','nombre'=>'CAMA DIVAN LAQUEADA TECHNODREAM  GRAVITY 1.5','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'CAMA DIVAN LAQUEADA TECHNODREAM  GRAVITY 1.5','precio'=>'2149','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1325001701','sku'=>'14631749','cadena_id'=>'SAGA','nombre'=>'CAMA DIVAN LAQUEADA TECHNODREAM  GRAVITY 2.0','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'CAMA DIVAN LAQUEADA TECHNODREAM  GRAVITY 2.0','precio'=>'2689','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1326001701','sku'=>'14631750','cadena_id'=>'SAGA','nombre'=>'CAMA DIVAN LAQUEADA TECHNODREAM  GRAVITY Q','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'CAMA DIVAN LAQUEADA TECHNODREAM  GRAVITY Q','precio'=>'3119','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1390002901','sku'=>'14017203','cadena_id'=>'SAGA','nombre'=>'CAMAROTE MALLORCA XEON(Camarote + Colchones 2plz; 1.5plz; 1plz)','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'CAMAROTE MALLORCA XEON(Camarote + Colchones 2plz; 1.5plz; 1plz)','precio'=>'3199','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1344000101','sku'=>'16475240','cadena_id'=>'SAGA','nombre'=>'PRACTIBOX AZUL POCKET OXYGEN 1.5','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'PRACTIBOX AZUL POCKET OXYGEN 1.5','precio'=>'1799','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1344000101','sku'=>'16475241','cadena_id'=>'SAGA','nombre'=>'PRACTIBOX AZUL POCKET OXYGEN 2.0','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'PRACTIBOX AZUL POCKET OXYGEN 2.0','precio'=>'2299','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1346000101','sku'=>'16475242','cadena_id'=>'SAGA','nombre'=>'PRACTIBOX AZUL POCKET OXYGEN Q','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'PRACTIBOX AZUL POCKET OXYGEN Q','precio'=>'2599','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1344001301','sku'=>'16475243','cadena_id'=>'SAGA','nombre'=>'PRACTIBOX MARRON POCKET OXYGEN 1.5','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'PRACTIBOX MARRON POCKET OXYGEN 1.5','precio'=>'1799','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1345001301','sku'=>'16475244','cadena_id'=>'SAGA','nombre'=>'PRACTIBOX MARRON POCKET OXYGEN 2.0','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'PRACTIBOX MARRON POCKET OXYGEN 2.0','precio'=>'2299','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1346001301','sku'=>'16475239','cadena_id'=>'SAGA','nombre'=>'PRACTIBOX MARRON POCKET OXYGEN Q','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'PRACTIBOX MARRON POCKET OXYGEN Q','precio'=>'2599','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1344000201','sku'=>'16475236','cadena_id'=>'SAGA','nombre'=>'PRACTIBOX GRIS POCKET OXYGEN 15','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'PRACTIBOX GRIS POCKET OXYGEN 15','precio'=>'1799','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1345000201','sku'=>'16475237','cadena_id'=>'SAGA','nombre'=>'PRACTIBOX GRIS POCKET OXYGEN 2.0','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'PRACTIBOX GRIS POCKET OXYGEN 2.0','precio'=>'2299','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1346000201','sku'=>'16475238','cadena_id'=>'SAGA','nombre'=>'PRACTIBOX GRIS POCKET OXYGEN Q','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'PRACTIBOX GRIS POCKET OXYGEN Q','precio'=>'2599','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1394000301','sku'=>'16415512','cadena_id'=>'SAGA','nombre'=>'KIT MADERA BLACK 1.5','categoria'=>'VARIOS','marca'=>'Technodream','descripcion'=>'KIT MADERA BLACK 1.5','precio'=>'399','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1395000301','sku'=>'16415513','cadena_id'=>'SAGA','nombre'=>'KIT MADERA BLACK 2.0','categoria'=>'VARIOS','marca'=>'Technodream','descripcion'=>'KIT MADERA BLACK 2.0','precio'=>'499','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1396000301','sku'=>'16415514','cadena_id'=>'SAGA','nombre'=>'KIT MADERA BLACK Q','categoria'=>'VARIOS','marca'=>'Technodream','descripcion'=>'KIT MADERA BLACK Q','precio'=>'549','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1194020001','sku'=>'12294016','cadena_id'=>'SAGA','nombre'=>'BASE NIDO 1.5','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'BASE NIDO 1.5','precio'=>'1199','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1195020001','sku'=>'12294019','cadena_id'=>'SAGA','nombre'=>'BASE NIDO 2.0','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'BASE NIDO 2.0','precio'=>'1399','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1114030401','sku'=>'16521666','cadena_id'=>'SAGA','nombre'=>'COMBO AMERICANO GRAVITY 1.5 PLZ','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'COMBO AMERICANO GRAVITY 1.5 PLZ','precio'=>'1799','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1115030401','sku'=>'16521667','cadena_id'=>'SAGA','nombre'=>'COMBO AMERICANO GRAVITY 2.0 PLZ','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'COMBO AMERICANO GRAVITY 2.0 PLZ','precio'=>'2149','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1116030401','sku'=>'16521668','cadena_id'=>'SAGA','nombre'=>'COMBO AMERICANO GRAVITY QUEEN','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'COMBO AMERICANO GRAVITY QUEEN','precio'=>'2799','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'1117030401','sku'=>'16521669','cadena_id'=>'SAGA','nombre'=>'COMBO AMERICANO GRAVITY KING','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'COMBO AMERICANO GRAVITY KING','precio'=>'3399','UNIDAD'=>'SET']);
        Producto::create(['sku_cic'=>'2114031001','sku'=>'16559701','cadena_id'=>'SAGA','nombre'=>'COLCHON RESORTE XEON 1.5Pz','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'COLCHON RESORTE XEON 1.5Pz','precio'=>'549','UNIDAD'=>'UND']);
        Producto::create(['sku_cic'=>'2115031001','sku'=>'16559702','cadena_id'=>'SAGA','nombre'=>'COLCHON RESORTE XEON 2Pz','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'COLCHON RESORTE XEON 2Pz','precio'=>'699','UNIDAD'=>'UND']);
        Producto::create(['sku_cic'=>'2124030201','sku'=>'16559703','cadena_id'=>'SAGA','nombre'=>'COLCHON POCKET OXYGEN 1.5Pz','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'COLCHON POCKET OXYGEN 1.5Pz','precio'=>'879','UNIDAD'=>'UND']);
        Producto::create(['sku_cic'=>'2125030201','sku'=>'16559704','cadena_id'=>'SAGA','nombre'=>'COLCHON POCKET OXYGEN 2Pz','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'COLCHON POCKET OXYGEN 2Pz','precio'=>'1059','UNIDAD'=>'UND']);
        Producto::create(['sku_cic'=>'2126030201','sku'=>'16559705','cadena_id'=>'SAGA','nombre'=>'COLCHON POCKET OXYGEN Q','categoria'=>'COLCHONES','marca'=>'Technodream','descripcion'=>'COLCHON POCKET OXYGEN Q','precio'=>'1359','UNIDAD'=>'UND']);

    }
}
