<?php

use Illuminate\Database\Seeder;
use App\MerchMaterial;

class MerchMaterialsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      MerchMaterial::create(['ciudad'=>'Trujillo','tipo_cliente'=>'Mayorista','marca'=>'Ricocan','codigo'=>'MER020','descripcion'=>'Gorros Ricocan 2019','escala'=>'1','mecanica'=>'Por La Compra De Medio Saco (7.5 Kg) + Húmedo']);
      MerchMaterial::create(['ciudad'=>'Trujillo','tipo_cliente'=>'Mayorista','marca'=>'Ricocan','codigo'=>'MER027','descripcion'=>'Tomatodo Ricocan 2019 + Plato Ricocan 2019','escala'=>'2','mecanica'=>'Por La Compra De 1 Saco (15Kg  A Más) + Húmedo']);
      MerchMaterial::create(['ciudad'=>'Trujillo','tipo_cliente'=>'Mayorista','marca'=>'Ricocan','codigo'=>'MER028','descripcion'=>'Tomatodo Ricocan 2019 + Polos Ricocan 2019','escala'=>'3','mecanica'=>'Por La Compra De 1.5 Sacos (22.5Kg A Más) + Húmedo']);
      MerchMaterial::create(['ciudad'=>'Trujillo','tipo_cliente'=>'Mayorista','marca'=>'Ricocat','codigo'=>'MER026','descripcion'=>'Gorros Ricocat 2019','escala'=>'1','mecanica'=>'Por La Compra De Medio Saco (4.5 Kg) + Húmedo']);
      MerchMaterial::create(['ciudad'=>'Trujillo','tipo_cliente'=>'Mayorista','marca'=>'Ricocat','codigo'=>'MER029','descripcion'=>'Tomatodo Ricocat 2019 + Plato Ricocat 2019','escala'=>'2','mecanica'=>'Por La Compra De 1 Saco (9Kg  A Más) + Húmedo']);
      MerchMaterial::create(['ciudad'=>'Trujillo','tipo_cliente'=>'Mayorista','marca'=>'Ricocat','codigo'=>'MER030','descripcion'=>'Cucharon Ricocat 2019 + Bolsa Deportiva Ricocat 2019','escala'=>'3','mecanica'=>'Por La Compra De 1.5 Sacos (13.5Kg A Más) + Húmedo']);
      MerchMaterial::create(['ciudad'=>'Trujillo','tipo_cliente'=>'Mayorista','marca'=>'Supercan','codigo'=>'MER003','descripcion'=>'Bolsas Notex Supercan','escala'=>'1','mecanica'=>'Por La Compra De 3 Kg ']);
      MerchMaterial::create(['ciudad'=>'Trujillo','tipo_cliente'=>'Mayorista','marca'=>'Supercan','codigo'=>'MER031','descripcion'=>'Plato Escudo Supercan + Vasos Medidores Supercan - Trade Tradicional','escala'=>'2','mecanica'=>'Por La Compra De Medio Saco (7.5 Kg)  ']);
      MerchMaterial::create(['ciudad'=>'Trujillo','tipo_cliente'=>'Mayorista','marca'=>'Supercan','codigo'=>'MER005','descripcion'=>'Polo En Algodon Jersey -Supercan/Supercat - Trade','escala'=>'3','mecanica'=>'Por La Compra De 1 Saco (15Kg  A Más)  ']);
      MerchMaterial::create(['ciudad'=>'Trujillo','tipo_cliente'=>'Mayorista','marca'=>'Supercat','codigo'=>'MER010','descripcion'=>'Mandil Taslan Supercat -Trade Tradicional','escala'=>'1','mecanica'=>'Por La Compra De 1 Saco']);
      MerchMaterial::create(['ciudad'=>'Trujillo','tipo_cliente'=>'Mayorista','marca'=>'Supercat','codigo'=>'MER032','descripcion'=>'Mandil Taslan Supercat -Trade Tradicional + Tomatodo Azul Supercat- Trade Tradicional','escala'=>'2','mecanica'=>'Por La Compra De 2 Sacos']);
      MerchMaterial::create(['ciudad'=>'Trujillo','tipo_cliente'=>'Mayorista','marca'=>'Supercat','codigo'=>'MER033','descripcion'=>'Polo Supercat En Algodón 30/1 Azul Cuello Redondo + Tomatodo Azul Supercat- Trade Tradicional','escala'=>'2','mecanica'=>'Por La Compra De 2 Sacos']);
      MerchMaterial::create(['ciudad'=>'Trujillo','tipo_cliente'=>'Mayorista','marca'=>'Supercat','codigo'=>'MER034','descripcion'=>'Bolsas Notex Supercat + Mandil Taslan Supercat -Trade Tradicional','escala'=>'3','mecanica'=>'Por La Compra De 3 Sacos A Más']);
      MerchMaterial::create(['ciudad'=>'Trujillo','tipo_cliente'=>'Mayorista','marca'=>'Supercat','codigo'=>'MER035','descripcion'=>'Bolsas Notex Supercat + Polo Supercat En Algodón 30/1 Azul Cuello Redondo','escala'=>'3','mecanica'=>'Por La Compra De 3 Sacos A Más']);
      MerchMaterial::create(['ciudad'=>'Trujillo','tipo_cliente'=>'Mayorista','marca'=>'Thor','codigo'=>'MER015','descripcion'=>'Polo Thor En Algodón 30/1 Amarillo Cuello Redondo','escala'=>'1','mecanica'=>'Por La Compra De 1/2 Saco']);
      MerchMaterial::create(['ciudad'=>'Trujillo','tipo_cliente'=>'Mayorista','marca'=>'Thor','codigo'=>'MER036','descripcion'=>'Polo Thor En Algodón 30/1 Amarillo Cuello Redondo + Pelotas Antiestres Amarilla Thor','escala'=>'2','mecanica'=>'Por La Compra De 2 Sacos']);
      MerchMaterial::create(['ciudad'=>'Trujillo','tipo_cliente'=>'Mayorista','marca'=>'Thor','codigo'=>'MER037','descripcion'=>'Polo Thor En Algodón 30/1 Amarillo Cuello Redondo + Bolsas Notex Thor','escala'=>'3','mecanica'=>'Por La Compra De 3 Sacos A Más']);
      MerchMaterial::create(['ciudad'=>'Trujillo','tipo_cliente'=>'Minorista','marca'=>'Ricocan','codigo'=>'MER018','descripcion'=>'Tomatodo Ricocan 2019','escala'=>'1','mecanica'=>'Por La Compra De 2 Kg + Húmedo']);
      MerchMaterial::create(['ciudad'=>'Trujillo','tipo_cliente'=>'Minorista','marca'=>'Ricocan','codigo'=>'MER019','descripcion'=>'Plato Ricocan 2019','escala'=>'2','mecanica'=>'Por La Compra De 3 Kg + Húmedo']);
      MerchMaterial::create(['ciudad'=>'Trujillo','tipo_cliente'=>'Minorista','marca'=>'Ricocan','codigo'=>'MER020','descripcion'=>'Gorros Ricocan 2019','escala'=>'3','mecanica'=>'Por La Compra De Medio Saco (7.5 Kg) + Húmedo']);
      MerchMaterial::create(['ciudad'=>'Trujillo','tipo_cliente'=>'Minorista','marca'=>'Ricocat','codigo'=>'MER038','descripcion'=>'Lapicero Ricocat','escala'=>'1','mecanica'=>'Por La Compra De 1/2 Kg']);
      MerchMaterial::create(['ciudad'=>'Trujillo','tipo_cliente'=>'Minorista','marca'=>'Ricocat','codigo'=>'MER022','descripcion'=>'Cucharon Ricocat 2019','escala'=>'2','mecanica'=>'Por La Compra De 1/2 Kg + Húmedo']);
      MerchMaterial::create(['ciudad'=>'Trujillo','tipo_cliente'=>'Minorista','marca'=>'Ricocat','codigo'=>'MER023','descripcion'=>'Tomatodo Ricocat 2019','escala'=>'3','mecanica'=>'Por La Compra De 1 Kg + Húmedo']);
      MerchMaterial::create(['ciudad'=>'Trujillo','tipo_cliente'=>'Minorista','marca'=>'Ricocat','codigo'=>'MER024','descripcion'=>'Plato Ricocat 2019','escala'=>'4','mecanica'=>'Por La Compra De 3 Kg + Húmedo']);
      MerchMaterial::create(['ciudad'=>'Trujillo','tipo_cliente'=>'Minorista','marca'=>'Ricocat','codigo'=>'MER026','descripcion'=>'Gorros Ricocat 2019','escala'=>'5','mecanica'=>'Por La Compra De Medio Saco (4.5 Kg) + Húmedo']);
      MerchMaterial::create(['ciudad'=>'Trujillo','tipo_cliente'=>'Minorista','marca'=>'Supercan','codigo'=>'MER002','descripcion'=>'Vasos Medidores Supercan - Trade Tradicional','escala'=>'1','mecanica'=>'Por La Compra De 1 Kg']);
      MerchMaterial::create(['ciudad'=>'Trujillo','tipo_cliente'=>'Minorista','marca'=>'Supercan','codigo'=>'MER039','descripcion'=>'Vaso Grande (Nuevo)','escala'=>'2','mecanica'=>'Por La Compra De 2 Kg  ']);
      MerchMaterial::create(['ciudad'=>'Trujillo','tipo_cliente'=>'Minorista','marca'=>'Supercan','codigo'=>'MER003','descripcion'=>'Bolsas Notex Supercan','escala'=>'3','mecanica'=>'Por La Compra 3 Kg']);
      MerchMaterial::create(['ciudad'=>'Trujillo','tipo_cliente'=>'Minorista','marca'=>'Supercan','codigo'=>'MER004','descripcion'=>'Plato Escudo Supercan','escala'=>'4','mecanica'=>'Por La Compra De 4 Kg']);
      MerchMaterial::create(['ciudad'=>'Trujillo','tipo_cliente'=>'Minorista','marca'=>'Supercat','codigo'=>'MER007','descripcion'=>'Gorro Taslan Supercat - Trade Tradicional','escala'=>'1','mecanica'=>'Por La Compra De 1 Kg']);
      MerchMaterial::create(['ciudad'=>'Trujillo','tipo_cliente'=>'Minorista','marca'=>'Supercat','codigo'=>'MER006','descripcion'=>'Vasos Medidores Supercat - Trade Tradicional','escala'=>'1','mecanica'=>'Por La Compra De 1 Kg']);
      MerchMaterial::create(['ciudad'=>'Trujillo','tipo_cliente'=>'Minorista','marca'=>'Supercat','codigo'=>'MER009','descripcion'=>'Tomatodo Azul Supercat- Trade Tradicional','escala'=>'2','mecanica'=>'Por La Compra De 2 Kg']);
      MerchMaterial::create(['ciudad'=>'Trujillo','tipo_cliente'=>'Minorista','marca'=>'Supercat','codigo'=>'MER008','descripcion'=>'Bolsas Notex Supercat','escala'=>'3','mecanica'=>'Por La Compra De 3 Kg']);
      MerchMaterial::create(['ciudad'=>'Trujillo','tipo_cliente'=>'Minorista','marca'=>'Thor','codigo'=>'MER013','descripcion'=>'Pelotas Antiestres Amarilla Thor','escala'=>'1','mecanica'=>'Por La Compra De 1 Kg Thor']);
      MerchMaterial::create(['ciudad'=>'Trujillo','tipo_cliente'=>'Minorista','marca'=>'Thor','codigo'=>'MER014','descripcion'=>'Bolsas Notex Thor','escala'=>'2','mecanica'=>'Por La Compra De 2 Kg Thor']);
      MerchMaterial::create(['ciudad'=>'Trujillo','tipo_cliente'=>'Minorista','marca'=>'Thor','codigo'=>'MER015','descripcion'=>'Polo Thor En Algodón 30/1 Amarillo Cuello Redondo','escala'=>'3','mecanica'=>'Por La Compra De 1/2 Saco (7.5Kg)']);
      MerchMaterial::create(['ciudad'=>'Chiclayo','tipo_cliente'=>'Todos los clientes','marca'=>'Ricocan','codigo'=>'MER017','descripcion'=>'Cucharon Ricocan 2019','escala'=>'1','mecanica'=>'Por La Compra De 1 Kg + Húmedo']);
      MerchMaterial::create(['ciudad'=>'Chiclayo','tipo_cliente'=>'Todos los clientes','marca'=>'Ricocan','codigo'=>'MER019','descripcion'=>'Plato Ricocan 2019','escala'=>'2','mecanica'=>'Por La Compra De 2 Kg + Húmedo']);
      MerchMaterial::create(['ciudad'=>'Chiclayo','tipo_cliente'=>'Todos los clientes','marca'=>'Ricocan','codigo'=>'MER021','descripcion'=>'Polos Ricocan 2019','escala'=>'3','mecanica'=>'Por La Compra De Medio Saco (7.5 Kg) + Húmedo']);
      MerchMaterial::create(['ciudad'=>'Chiclayo','tipo_cliente'=>'Todos los clientes','marca'=>'Ricocat','codigo'=>'MER040','descripcion'=>'Vasos Medidores Ricocat 2019','escala'=>'1','mecanica'=>'Por La Compra De 1 Kg']);
      MerchMaterial::create(['ciudad'=>'Chiclayo','tipo_cliente'=>'Todos los clientes','marca'=>'Ricocat','codigo'=>'MER023','descripcion'=>'Tomatodo Ricocat 2019','escala'=>'2','mecanica'=>'Por La Compra De 3/4 Kg + Húmedo']);
      MerchMaterial::create(['ciudad'=>'Chiclayo','tipo_cliente'=>'Todos los clientes','marca'=>'Ricocat','codigo'=>'MER024','descripcion'=>'Plato Ricocat 2019','escala'=>'3','mecanica'=>'Por La Compra De 1.5 Kg + Húmedo']);
      MerchMaterial::create(['ciudad'=>'Chiclayo','tipo_cliente'=>'Todos los clientes','marca'=>'Ricocat','codigo'=>'MER041','descripcion'=>'Polos Ricocat 2019','escala'=>'4','mecanica'=>'Por La Compra De Medio Saco (4.5 Kg) + Húmedo']);
      MerchMaterial::create(['ciudad'=>'Chiclayo','tipo_cliente'=>'Todos los clientes','marca'=>'Supercan','codigo'=>'MER001','descripcion'=>'Llavero Abridor Supercan','escala'=>'1','mecanica'=>'Por La Compra De 1/2 Kg']);
      MerchMaterial::create(['ciudad'=>'Chiclayo','tipo_cliente'=>'Todos los clientes','marca'=>'Supercan','codigo'=>'MER002','descripcion'=>'Vasos Medidores Supercan - Trade Tradicional','escala'=>'2','mecanica'=>'Por La Compra De 1 Kg']);
      MerchMaterial::create(['ciudad'=>'Chiclayo','tipo_cliente'=>'Todos los clientes','marca'=>'Supercan','codigo'=>'MER003','descripcion'=>'Bolsas Notex Supercan','escala'=>'3','mecanica'=>'Por La Compra De 2 Kg  ']);
      MerchMaterial::create(['ciudad'=>'Chiclayo','tipo_cliente'=>'Todos los clientes','marca'=>'Supercan','codigo'=>'MER004','descripcion'=>'Plato Escudo Supercan','escala'=>'4','mecanica'=>'Por La Compra De Medio Saco (7.5 Kg)']);
      MerchMaterial::create(['ciudad'=>'Chiclayo','tipo_cliente'=>'Todos los clientes','marca'=>'Supercat','codigo'=>'MER006','descripcion'=>'Vasos Medidores Supercat - Trade Tradicional','escala'=>'1','mecanica'=>'Por La Compra De 1 Kg']);
      MerchMaterial::create(['ciudad'=>'Chiclayo','tipo_cliente'=>'Todos los clientes','marca'=>'Supercat','codigo'=>'MER008','descripcion'=>'Bolsas Notex Supercat','escala'=>'2','mecanica'=>'Por La Compra De 1.5 Kg']);
      MerchMaterial::create(['ciudad'=>'Chiclayo','tipo_cliente'=>'Todos los clientes','marca'=>'Supercat','codigo'=>'MER005','descripcion'=>'Polo En Algodon Jersey -Supercan/Supercat - Trade','escala'=>'3','mecanica'=>'Por La Compra De Medio Saco (4.5 Kg)']);
      MerchMaterial::create(['ciudad'=>'Chiclayo','tipo_cliente'=>'Todos los clientes','marca'=>'Thor','codigo'=>'MER013','descripcion'=>'Pelotas Antiestres Amarilla Thor','escala'=>'1','mecanica'=>'Por La Compra De 1 Kg Thor']);
      MerchMaterial::create(['ciudad'=>'Chiclayo','tipo_cliente'=>'Todos los clientes','marca'=>'Thor','codigo'=>'MER014','descripcion'=>'Bolsas Notex Thor','escala'=>'2','mecanica'=>'Por La Compra De 2 Kg Thor']);
      MerchMaterial::create(['ciudad'=>'Chiclayo','tipo_cliente'=>'Todos los clientes','marca'=>'Thor','codigo'=>'MER015','descripcion'=>'Polo Thor En Algodón 30/1 Amarillo Cuello Redondo','escala'=>'3','mecanica'=>'Por La Compra De 1/2 Saco (7.5Kg)']);
      MerchMaterial::create(['ciudad'=>'Piura','tipo_cliente'=>'Todos los clientes','marca'=>'Supercan','codigo'=>'MER001','descripcion'=>'Llavero Abridor Supercan','escala'=>'1','mecanica'=>'Por la compra de 1 kg']);
      MerchMaterial::create(['ciudad'=>'Piura','tipo_cliente'=>'Todos los clientes','marca'=>'Supercan','codigo'=>'MER002','descripcion'=>'Vasos Medidores Supercan - Trade Tradicional','escala'=>'2','mecanica'=>'Por la compra de 2 kg']);
      MerchMaterial::create(['ciudad'=>'Piura','tipo_cliente'=>'Todos los clientes','marca'=>'Supercan','codigo'=>'MER003','descripcion'=>'Bolsas Notex Supercan','escala'=>'3','mecanica'=>'Por la compra de 3 kg']);
      MerchMaterial::create(['ciudad'=>'Piura','tipo_cliente'=>'Todos los clientes','marca'=>'Supercan','codigo'=>'MER004','descripcion'=>'Plato Escudo Supercan','escala'=>'4','mecanica'=>'Por la compra de medio saco (7.5 kg)']);
      MerchMaterial::create(['ciudad'=>'Piura','tipo_cliente'=>'Todos los clientes','marca'=>'Supercan','codigo'=>'MER005','descripcion'=>'Polo En Algodon Jersey -Supercan/Supercat - Trade','escala'=>'5','mecanica'=>'Por la compra de un saco (15 o 25 kg)']);
      MerchMaterial::create(['ciudad'=>'Piura','tipo_cliente'=>'Todos los clientes','marca'=>'Supercat','codigo'=>'MER006','descripcion'=>'Vasos Medidores Supercat - Trade Tradicional','escala'=>'1','mecanica'=>'Por la compra de 1/2 kg']);
      MerchMaterial::create(['ciudad'=>'Piura','tipo_cliente'=>'Todos los clientes','marca'=>'Supercat','codigo'=>'MER007','descripcion'=>'Gorro Taslan Supercat - Trade Tradicional','escala'=>'1','mecanica'=>'Por la compra de 1/2 kg']);
      MerchMaterial::create(['ciudad'=>'Piura','tipo_cliente'=>'Todos los clientes','marca'=>'Supercat','codigo'=>'MER008','descripcion'=>'Bolsas Notex Supercat','escala'=>'2','mecanica'=>'Por la compra de 1.5 kg']);
      MerchMaterial::create(['ciudad'=>'Piura','tipo_cliente'=>'Todos los clientes','marca'=>'Supercat','codigo'=>'MER009','descripcion'=>'Tomatodo Azul Supercat- Trade Tradicional','escala'=>'3','mecanica'=>'Por la compra de 2 kg']);
      MerchMaterial::create(['ciudad'=>'Piura','tipo_cliente'=>'Todos los clientes','marca'=>'Supercat','codigo'=>'MER010','descripcion'=>'Mandil Taslan Supercat -Trade Tradicional','escala'=>'4','mecanica'=>'Por la compra de medio saco (4.5 kg)']);
      MerchMaterial::create(['ciudad'=>'Piura','tipo_cliente'=>'Todos los clientes','marca'=>'Supercat','codigo'=>'MER011','descripcion'=>'Polo Supercat En Algodón 30/1 Azul Cuello Redondo','escala'=>'5','mecanica'=>'Por la compra de un saco (9 kg)']);
      MerchMaterial::create(['ciudad'=>'Piura','tipo_cliente'=>'Todos los clientes','marca'=>'Thor','codigo'=>'MER012','descripcion'=>'Vasos Medidores Thor - Trade Tradicional','escala'=>'1','mecanica'=>'Por la compra de 2 kg']);
      MerchMaterial::create(['ciudad'=>'Piura','tipo_cliente'=>'Todos los clientes','marca'=>'Thor','codigo'=>'MER013','descripcion'=>'Pelotas Antiestres Amarilla Thor','escala'=>'2','mecanica'=>'Por la compra de 3 kg']);
      MerchMaterial::create(['ciudad'=>'Piura','tipo_cliente'=>'Todos los clientes','marca'=>'Thor','codigo'=>'MER014','descripcion'=>'Bolsas Notex Thor','escala'=>'3','mecanica'=>'Por la compra de medio saco (7.5 kg)']);
      MerchMaterial::create(['ciudad'=>'Piura','tipo_cliente'=>'Todos los clientes','marca'=>'Thor','codigo'=>'MER015','descripcion'=>'Polo Thor En Algodón 30/1 Amarillo Cuello Redondo','escala'=>'4','mecanica'=>'Por la compra de un saco (15 o 25 kg)']);
      MerchMaterial::create(['ciudad'=>'Piura','tipo_cliente'=>'Todos los clientes','marca'=>'Ricocan','codigo'=>'MER016','descripcion'=>'Frisbee Ricocan 2019','escala'=>'1','mecanica'=>'Por la compra de 1 kg + húmedo']);
      MerchMaterial::create(['ciudad'=>'Piura','tipo_cliente'=>'Todos los clientes','marca'=>'Ricocan','codigo'=>'MER017','descripcion'=>'Cucharon Ricocan 2019','escala'=>'1','mecanica'=>'Por la compra de 1 kg + húmedo']);
      MerchMaterial::create(['ciudad'=>'Piura','tipo_cliente'=>'Todos los clientes','marca'=>'Ricocan','codigo'=>'MER018','descripcion'=>'Tomatodo Ricocan 2019','escala'=>'2','mecanica'=>'Por la compra de 2 kg + húmedo']);
      MerchMaterial::create(['ciudad'=>'Piura','tipo_cliente'=>'Todos los clientes','marca'=>'Ricocan','codigo'=>'MER019','descripcion'=>'Plato Ricocan 2019','escala'=>'3','mecanica'=>'Por la compra de 3 kg + húmedo']);
      MerchMaterial::create(['ciudad'=>'Piura','tipo_cliente'=>'Todos los clientes','marca'=>'Ricocan','codigo'=>'MER020','descripcion'=>'Gorros Ricocan 2019','escala'=>'4','mecanica'=>'Por la compra de medio saco (7.5 kg)']);
      MerchMaterial::create(['ciudad'=>'Piura','tipo_cliente'=>'Todos los clientes','marca'=>'Ricocan','codigo'=>'MER021','descripcion'=>'Polos Ricocan 2019','escala'=>'5','mecanica'=>'Por la compra de un saco (15 o 25 kg)']);
      MerchMaterial::create(['ciudad'=>'Piura','tipo_cliente'=>'Todos los clientes','marca'=>'Ricocat','codigo'=>'MER022','descripcion'=>'Cucharon Ricocat 2019','escala'=>'1','mecanica'=>'Por la compra de 1/2 kg + húmedo']);
      MerchMaterial::create(['ciudad'=>'Piura','tipo_cliente'=>'Todos los clientes','marca'=>'Ricocat','codigo'=>'MER023','descripcion'=>'Tomatodo Ricocat 2019','escala'=>'2','mecanica'=>'Por la compra de 1 kg + húmedo']);
      MerchMaterial::create(['ciudad'=>'Piura','tipo_cliente'=>'Todos los clientes','marca'=>'Ricocat','codigo'=>'MER024','descripcion'=>'Plato Ricocat 2019','escala'=>'3','mecanica'=>'Por la compra de 2 kg + húmedo']);
      MerchMaterial::create(['ciudad'=>'Piura','tipo_cliente'=>'Todos los clientes','marca'=>'Ricocat','codigo'=>'MER025','descripcion'=>'Bolsa Deportiva Ricocat 2019','escala'=>'4','mecanica'=>'Por la compra de medio saco (4.5 kg)']);
      MerchMaterial::create(['ciudad'=>'Piura','tipo_cliente'=>'Todos los clientes','marca'=>'Ricocat','codigo'=>'MER026','descripcion'=>'Gorros Ricocat 2019','escala'=>'5','mecanica'=>'Por la compra de un saco (9 kg)']);
      MerchMaterial::create(['ciudad'=>'Arequipa','tipo_cliente'=>'Todos los clientes','marca'=>'Supercan','codigo'=>'MER001','descripcion'=>'Llavero Abridor Supercan','escala'=>'1','mecanica'=>'Por la compra de 1 kg + húmedo']);
      MerchMaterial::create(['ciudad'=>'Arequipa','tipo_cliente'=>'Todos los clientes','marca'=>'Supercan','codigo'=>'MER002','descripcion'=>'Vasos Medidores Supercan - Trade Tradicional','escala'=>'2','mecanica'=>'Por la compra de 2 kg + húmedo']);
      MerchMaterial::create(['ciudad'=>'Arequipa','tipo_cliente'=>'Todos los clientes','marca'=>'Supercan','codigo'=>'MER003','descripcion'=>'Bolsas Notex Supercan','escala'=>'3','mecanica'=>'Por la compra de 3 kg + húmedo']);
      MerchMaterial::create(['ciudad'=>'Arequipa','tipo_cliente'=>'Todos los clientes','marca'=>'Supercan','codigo'=>'MER004','descripcion'=>'Plato Escudo Supercan','escala'=>'4','mecanica'=>'Por la compra de medio saco (7.5 kg)']);
      MerchMaterial::create(['ciudad'=>'Arequipa','tipo_cliente'=>'Todos los clientes','marca'=>'Supercan','codigo'=>'MER005','descripcion'=>'Polo En Algodon Jersey -Supercan/Supercat - Trade','escala'=>'5','mecanica'=>'Por la compra de un saco (15 o 25 kg)']);
      MerchMaterial::create(['ciudad'=>'Arequipa','tipo_cliente'=>'Todos los clientes','marca'=>'Supercat','codigo'=>'MER006','descripcion'=>'Vasos Medidores Supercat - Trade Tradicional','escala'=>'1','mecanica'=>'Por la compra de 1 kg + húmedo']);
      MerchMaterial::create(['ciudad'=>'Arequipa','tipo_cliente'=>'Todos los clientes','marca'=>'Supercat','codigo'=>'MER007','descripcion'=>'Gorro Taslan Supercat - Trade Tradicional','escala'=>'1','mecanica'=>'Por la compra de 1 kg + húmedo']);
      MerchMaterial::create(['ciudad'=>'Arequipa','tipo_cliente'=>'Todos los clientes','marca'=>'Supercat','codigo'=>'MER008','descripcion'=>'Bolsas Notex Supercat','escala'=>'2','mecanica'=>'Por la compra de 2 kg + húmedo']);
      MerchMaterial::create(['ciudad'=>'Arequipa','tipo_cliente'=>'Todos los clientes','marca'=>'Supercat','codigo'=>'MER009','descripcion'=>'Tomatodo Azul Supercat- Trade Tradicional','escala'=>'3','mecanica'=>'Por la compra de 3 kg + húmedo']);
      MerchMaterial::create(['ciudad'=>'Arequipa','tipo_cliente'=>'Todos los clientes','marca'=>'Supercat','codigo'=>'MER010','descripcion'=>'Mandil Taslan Supercat -Trade Tradicional','escala'=>'4','mecanica'=>'Por la compra de medio saco (4.5 kg)']);
      MerchMaterial::create(['ciudad'=>'Arequipa','tipo_cliente'=>'Todos los clientes','marca'=>'Supercat','codigo'=>'MER011','descripcion'=>'Polo Supercat En Algodón 30/1 Azul Cuello Redondo','escala'=>'5','mecanica'=>'Por la compra de un saco (9 kg)']);
      MerchMaterial::create(['ciudad'=>'Arequipa','tipo_cliente'=>'Todos los clientes','marca'=>'Thor','codigo'=>'MER012','descripcion'=>'Vasos Medidores Thor - Trade Tradicional','escala'=>'1','mecanica'=>'Por la compra de 2 kg + húmedo']);
      MerchMaterial::create(['ciudad'=>'Arequipa','tipo_cliente'=>'Todos los clientes','marca'=>'Thor','codigo'=>'MER013','descripcion'=>'Pelotas Antiestres Amarilla Thor','escala'=>'2','mecanica'=>'Por la compra de 3 kg + húmedo']);
      MerchMaterial::create(['ciudad'=>'Arequipa','tipo_cliente'=>'Todos los clientes','marca'=>'Thor','codigo'=>'MER014','descripcion'=>'Bolsas Notex Thor','escala'=>'3','mecanica'=>'Por la compra de medio saco (7.5 kg)']);
      MerchMaterial::create(['ciudad'=>'Arequipa','tipo_cliente'=>'Todos los clientes','marca'=>'Thor','codigo'=>'MER015','descripcion'=>'Polo Thor En Algodón 30/1 Amarillo Cuello Redondo','escala'=>'4','mecanica'=>'Por la compra de un saco (15 o 25 kg)']);
      MerchMaterial::create(['ciudad'=>'Arequipa','tipo_cliente'=>'Todos los clientes','marca'=>'Ricocan','codigo'=>'MER018','descripcion'=>'Cucharon Ricocan 2019','escala'=>'1','mecanica'=>'Por la compra de 1 kg + húmedo']);
      MerchMaterial::create(['ciudad'=>'Arequipa','tipo_cliente'=>'Todos los clientes','marca'=>'Ricocan','codigo'=>'MER016','descripcion'=>'Tomatodo Ricocan 2019','escala'=>'2','mecanica'=>'Por la compra de 2 kg + húmedo']);
      MerchMaterial::create(['ciudad'=>'Arequipa','tipo_cliente'=>'Todos los clientes','marca'=>'Ricocan','codigo'=>'MER017','descripcion'=>'Frisbee Ricocan 2019','escala'=>'2','mecanica'=>'Por la compra de 2 kg + húmedo']);
      MerchMaterial::create(['ciudad'=>'Arequipa','tipo_cliente'=>'Todos los clientes','marca'=>'Ricocan','codigo'=>'MER019','descripcion'=>'Plato Ricocan 2019','escala'=>'3','mecanica'=>'Por la compra de 3 kg + húmedo']);
      MerchMaterial::create(['ciudad'=>'Arequipa','tipo_cliente'=>'Todos los clientes','marca'=>'Ricocan','codigo'=>'MER020','descripcion'=>'Gorros Ricocan 2019','escala'=>'4','mecanica'=>'Por la compra de medio saco (7.5 kg)']);
      MerchMaterial::create(['ciudad'=>'Arequipa','tipo_cliente'=>'Todos los clientes','marca'=>'Ricocan','codigo'=>'MER021','descripcion'=>'Polos Ricocan 2019','escala'=>'5','mecanica'=>'Por la compra de un saco (15 o 25 kg)']);
      MerchMaterial::create(['ciudad'=>'Arequipa','tipo_cliente'=>'Todos los clientes','marca'=>'Ricocat','codigo'=>'MER022','descripcion'=>'Cucharon Ricocat 2019','escala'=>'1','mecanica'=>'Por la compra de 1 kg + húmedo']);
      MerchMaterial::create(['ciudad'=>'Arequipa','tipo_cliente'=>'Todos los clientes','marca'=>'Ricocat','codigo'=>'MER023','descripcion'=>'Tomatodo Ricocat 2019','escala'=>'2','mecanica'=>'Por la compra de 2 kg + húmedo']);
      MerchMaterial::create(['ciudad'=>'Arequipa','tipo_cliente'=>'Todos los clientes','marca'=>'Ricocat','codigo'=>'MER024','descripcion'=>'Plato Ricocat 2019','escala'=>'3','mecanica'=>'Por la compra de 3 kg + húmedo']);
      MerchMaterial::create(['ciudad'=>'Arequipa','tipo_cliente'=>'Todos los clientes','marca'=>'Ricocat','codigo'=>'MER025','descripcion'=>'Bolsa Deportiva Ricocat 2019','escala'=>'4','mecanica'=>'Por la compra de medio saco (4.5 kg)']);
      MerchMaterial::create(['ciudad'=>'Arequipa','tipo_cliente'=>'Todos los clientes','marca'=>'Ricocat','codigo'=>'MER026','descripcion'=>'Gorros Ricocat 2019','escala'=>'5','mecanica'=>'Por la compra de un saco (9 kg)']);

    }
}
