<?php

use Illuminate\Database\Seeder;
use App\Cadena;
use App\User;
use App\Tienda;
use Faker\Factory;
use App\Producto;

class SetimaCargaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

      Producto::create(['sku_cic'=>'2125040601','sku'=>'15705486','cadena_id'=>'8','nombre'=>'COLCHON RECHARGE LUXURY FIRM 2 PLZ','categoria'=>'COLCHONES','marca'=>'SIMMONS','descripcion'=>'COLCHÓN RECHARGE LUXURY FIRM 2 PLZ','precio'=>'2799','UNIDAD'=>'UND']);
      Producto::create(['sku_cic'=>'2125040701','sku'=>'14862464','cadena_id'=>'8','nombre'=>'COLCHON RECHARGE LUXURY FIRM PT 2 P','categoria'=>'COLCHONES','marca'=>'SIMMONS','descripcion'=>'COLCHON RECHARGE LUXURY FIRM PT 2 P','precio'=>'3199','UNIDAD'=>'UND']);
      Producto::create(['sku_cic'=>'2127040701','sku'=>'14862466','cadena_id'=>'8','nombre'=>'COLCHON RECHARGE LUXURY FIRM PT KS','categoria'=>'COLCHONES','marca'=>'SIMMONS','descripcion'=>'COLCHON RECHARGE LUXURY FIRM PT KS','precio'=>'4449','UNIDAD'=>'UND']);
      Producto::create(['sku_cic'=>'2127040601','sku'=>'14862463','cadena_id'=>'8','nombre'=>'COLCHON RECHARGE LUXURY FIRM KS','categoria'=>'COLCHONES','marca'=>'SIMMONS','descripcion'=>'COLCHON RECHARGE LUXURY FIRM KS','precio'=>'3899','UNIDAD'=>'UND']);
      Producto::create(['sku_cic'=>'2126040701','sku'=>'14862465','cadena_id'=>'8','nombre'=>'COLCHON RECHARGE LUXURY FIRM PT QS','categoria'=>'COLCHONES','marca'=>'SIMMONS','descripcion'=>'COLCHON RECHARGE LUXURY FIRM PT QS','precio'=>'3699','UNIDAD'=>'UND']);
      Producto::create(['sku_cic'=>'2126040601','sku'=>'14862462','cadena_id'=>'8','nombre'=>'COLCHON RECHARGE LUXURY FIRM QS','categoria'=>'COLCHONES','marca'=>'SIMMONS','descripcion'=>'COLCHON RECHARGE LUXURY FIRM QS','precio'=>'3199','UNIDAD'=>'UND']);
      Producto::create(['sku_cic'=>'1116040005','sku'=>'14862485','cadena_id'=>'8','nombre'=>'CAMA AMERICANA RECHARGE LUXURY FIRM PT QS','categoria'=>'COLCHONES','marca'=>'SIMMONS','descripcion'=>'CAMA AMERICANA RECHARGE LUXURY FIRM PT QS','precio'=>'4999','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'1116040301','sku'=>'14862482','cadena_id'=>'8','nombre'=>'CAMA AMERICANA RECHARGE LUXURY FIRM QS','categoria'=>'COLCHONES','marca'=>'SIMMONS','descripcion'=>'CAMA AMERICANA RECHARGE LUXURY FIRM QS','precio'=>'3999','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'1117040301','sku'=>'15705490','cadena_id'=>'8','nombre'=>'CAMA AMERICANA RECHARGE LUXURY FIRM KS','categoria'=>'COLCHONES','marca'=>'SIMMONS','descripcion'=>'CAMA AMERICANA RECHARGE LUXURY FIRM KS','precio'=>'5599','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'1117040005','sku'=>'14862486','cadena_id'=>'8','nombre'=>'CAMA AMERICANA RECHARGE LUXURY FIRM PT KS','categoria'=>'COLCHONES','marca'=>'SIMMONS','descripcion'=>'CAMA AMERICANA RECHARGE LUXURY FIRM PT KS','precio'=>'6149','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'1115040301','sku'=>'15705491','cadena_id'=>'8','nombre'=>'CAMA AMERICANA RECHARGE LUXURY FIRM 2 PLZ','categoria'=>'COLCHONES','marca'=>'SIMMONS','descripcion'=>'CAMA AMERICANA RECHARGE LUXURY FIRM 2 PLZ','precio'=>'3749','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'1115040001','sku'=>'14862484','cadena_id'=>'8','nombre'=>'CAM AM.RECHARGE LUXURY FIRM PT 2 PL','categoria'=>'COLCHONES','marca'=>'SIMMONS','descripcion'=>'CAM AM.RECHARGE LUXURY FIRM PT 2 PL','precio'=>'4149','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'2115040101','sku'=>'15812360','cadena_id'=>'8','nombre'=>'COLCHON SIMMONS BEAUTYSLEEP ERICA LUXURY FIRM PT 2 PLAZAS','categoria'=>'COLCHONES','marca'=>'SIMMONS','descripcion'=>'COLCHON SIMMONS BEAUTYSLEEP ERICA LUXURY FIRM PT 2 PLAZAS','precio'=>'2199','UNIDAD'=>'UND']);
      Producto::create(['sku_cic'=>'2116040101','sku'=>'15812361','cadena_id'=>'8','nombre'=>'COLCHON SIMMONS BEAUTYSLEEP ERICA LUXURY FIRM PT QUEEN','categoria'=>'COLCHONES','marca'=>'SIMMONS','descripcion'=>'COLCHON SIMMONS BEAUTYSLEEP ERICA LUXURY FIRM PT QUEEN','precio'=>'2599','UNIDAD'=>'UND']);
      Producto::create(['sku_cic'=>'2117040101','sku'=>'15812362','cadena_id'=>'8','nombre'=>'COLCHON SIMMONS BEAUTYSLEEP ERICA LUXURY FIRM PT KING','categoria'=>'COLCHONES','marca'=>'SIMMONS','descripcion'=>'COLCHON SIMMONS BEAUTYSLEEP ERICA LUXURY FIRM PT KING','precio'=>'3099','UNIDAD'=>'UND']);
      Producto::create(['sku_cic'=>'1115040101','sku'=>'15812363','cadena_id'=>'8','nombre'=>'CAMA AMERICANA SIMMONS BEAUTYSLEEP ERICA LUXURY FIRM PT 2','categoria'=>'COLCHONES','marca'=>'SIMMONS','descripcion'=>'CAMA AMERICANA SIMMONS BEAUTYSLEEP ERICA LUXURY FIRM PT 2','precio'=>'3099','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'1116040101','sku'=>'15812364','cadena_id'=>'8','nombre'=>'CAMA AMERICANA SIMMONS BEAUTYSLEEP ERICA LUXURY FIRM PT QUEEN','categoria'=>'COLCHONES','marca'=>'SIMMONS','descripcion'=>'CAMA AMERICANA SIMMONS BEAUTYSLEEP ERICA LUXURY FIRM PT QUEEN','precio'=>'3799','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'1117040101','sku'=>'15812365','cadena_id'=>'8','nombre'=>'CAMA AMERICANA SIMMONS BEAUTYSLEEP ERICA LUXURY FIRM PT KING','categoria'=>'COLCHONES','marca'=>'SIMMONS','descripcion'=>'CAMA AMERICANA SIMMONS BEAUTYSLEEP ERICA LUXURY FIRM PT KING','precio'=>'4799','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'1115040401','sku'=>'15883721','cadena_id'=>'8','nombre'=>'CAMA AMERICANA SIMMONS BEAUTYREST PLATINUM PT 2 PLAZAS','categoria'=>'COLCHONES','marca'=>'SIMMONS','descripcion'=>'CAMA AMERICANA SIMMONS BEAUTYREST PLATINUM PT 2 PLAZAS','precio'=>'6549','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'1116040401','sku'=>'15883722','cadena_id'=>'8','nombre'=>'CAMA AMERICANA SIMMONS BEAUTYREST PLATINUM PT QUEEN','categoria'=>'COLCHONES','marca'=>'SIMMONS','descripcion'=>'CAMA AMERICANA SIMMONS BEAUTYREST PLATINUM PT QUEEN','precio'=>'7249','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'1117040401','sku'=>'15883723','cadena_id'=>'8','nombre'=>'CAMA AMERICANA SIMMONS BEAUTYREST PLATINUM PT KING','categoria'=>'COLCHONES','marca'=>'SIMMONS','descripcion'=>'CAMA AMERICANA SIMMONS BEAUTYREST PLATINUM PT KING','precio'=>'8949','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'2125040401','sku'=>'15184260','cadena_id'=>'8','nombre'=>'COLCHON RESORTE FELICITY 2PZ','categoria'=>'COLCHONES','marca'=>'SIMMONS','descripcion'=>'COLCHON RESORTE FELICITY 2PZ','precio'=>'2699','UNIDAD'=>'UND']);
      Producto::create(['sku_cic'=>'2126040401','sku'=>'15184261','cadena_id'=>'8','nombre'=>'COLCHON RESORTE FELICITY Q','categoria'=>'COLCHONES','marca'=>'SIMMONS','descripcion'=>'COLCHON RESORTE FELICITY Q','precio'=>'3099','UNIDAD'=>'UND']);
      Producto::create(['sku_cic'=>'2127040401','sku'=>'15184262','cadena_id'=>'8','nombre'=>'COLCHON RESORTE FELICITY K','categoria'=>'COLCHONES','marca'=>'SIMMONS','descripcion'=>'COLCHON RESORTE FELICITY K','precio'=>'3799','UNIDAD'=>'UND']);
      Producto::create(['sku_cic'=>'1115041101','sku'=>'15184263','cadena_id'=>'8','nombre'=>'CAMA AMERICANA FELICITY 2PZ','categoria'=>'COLCHONES','marca'=>'SIMMONS','descripcion'=>'CAMA AMERICANA FELICITY 2PZ','precio'=>'3699','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'1116041101','sku'=>'15184264','cadena_id'=>'8','nombre'=>'CAMA AMERICANA FELICITY Q','categoria'=>'COLCHONES','marca'=>'SIMMONS','descripcion'=>'CAMA AMERICANA FELICITY Q','precio'=>'4399','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'1117041101','sku'=>'15184265','cadena_id'=>'8','nombre'=>'CAMA AMERICANA FELICITY K','categoria'=>'COLCHONES','marca'=>'SIMMONS','descripcion'=>'CAMA AMERICANA FELICITY K','precio'=>'5599','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'1115040501','sku'=>'16751203','cadena_id'=>'8','nombre'=>'CAMA AMERICANA SIMMONS BEAUTYREST SILVER PT 2 PLZ','categoria'=>'COLCHONES','marca'=>'SIMMONS','descripcion'=>'CAMA AMERICANA SIMMONS BEAUTYREST SILVER PT 2 PLZ','precio'=>'4149','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'1116040501','sku'=>'16751204','cadena_id'=>'8','nombre'=>'CAMA AMERICANA SIMMONS BEAUTYREST SILVER PT QUEEN','categoria'=>'COLCHONES','marca'=>'SIMMONS','descripcion'=>'CAMA AMERICANA SIMMONS BEAUTYREST SILVER PT QUEEN','precio'=>'4999','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'1117040501','sku'=>'16751205','cadena_id'=>'8','nombre'=>'CAMA AMERICANA SIMMONS BEAUTYREST SILVER PT KING','categoria'=>'COLCHONES','marca'=>'SIMMONS','descripcion'=>'CAMA AMERICANA SIMMONS BEAUTYREST SILVER PT KING','precio'=>'6149','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'1000000000','sku'=>'16905169','cadena_id'=>'8','nombre'=>'CAMA PRACTIBOX GRIS RECHARGE LUXURY FIRM PT QS','categoria'=>'COLCHONES','marca'=>'SIMMONS','descripcion'=>'CAMA PRACTIBOX GRIS RECHARGE LUXURY FIRM PT QS','precio'=>'4999','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'1000000000','sku'=>'16905170','cadena_id'=>'8','nombre'=>'CAM PRACTIBOX GRIS RECHARGE LUXURY FIRM PT 2 PL','categoria'=>'COLCHONES','marca'=>'SIMMONS','descripcion'=>'CAM PRACTIBOX GRIS RECHARGE LUXURY FIRM PT 2 PL','precio'=>'4149','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'1000000000','sku'=>'16905171','cadena_id'=>'8','nombre'=>'CAMA CAJONES RECHARGE LUXURY FIRM PT KS','categoria'=>'COLCHONES','marca'=>'SIMMONS','descripcion'=>'CAMA CAJONES RECHARGE LUXURY FIRM PT KS','precio'=>'6149','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'1000000000','sku'=>'16905172','cadena_id'=>'8','nombre'=>'CAMA CAJONES  RECHARGE LUXURY FIRM PT QS','categoria'=>'COLCHONES','marca'=>'SIMMONS','descripcion'=>'CAMA CAJONES  RECHARGE LUXURY FIRM PT QS','precio'=>'4999','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'1000000000','sku'=>'16905173','cadena_id'=>'8','nombre'=>'CAMA CAJONES .RECHARGE LUXURY FIRM PT 2 PL','categoria'=>'COLCHONES','marca'=>'SIMMONS','descripcion'=>'CAMA CAJONES .RECHARGE LUXURY FIRM PT 2 PL','precio'=>'4149','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'1346001401','sku'=>'16905174','cadena_id'=>'8','nombre'=>'CAMA PRACTIBOX GRIS SIMMONS BEAUTYREST PLATINUM PT 2 PL','categoria'=>'COLCHONES','marca'=>'SIMMONS','descripcion'=>'CAMA PRACTIBOX GRIS SIMMONS BEAUTYREST PLATINUM PT 2 PL','precio'=>'6549','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'1347001401','sku'=>'16905231','cadena_id'=>'8','nombre'=>'CAMA PRACTIBOX GRIS SIMMONS BEAUTYREST PLATINUM PT QUEEN','categoria'=>'COLCHONES','marca'=>'SIMMONS','descripcion'=>'CAMA PRACTIBOX GRIS SIMMONS BEAUTYREST PLATINUM PT QUEEN','precio'=>'7249','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'1000000000','sku'=>'16905175','cadena_id'=>'8','nombre'=>'CAMA CAJONES SIMMONS BEAUTYREST PLATINUM PT 2 PL','categoria'=>'COLCHONES','marca'=>'SIMMONS','descripcion'=>'CAMA CAJONES SIMMONS BEAUTYREST PLATINUM PT 2 PL','precio'=>'6549','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'1000000000','sku'=>'16905176','cadena_id'=>'8','nombre'=>'CAMA CAJONES SIMMONS BEAUTYREST PLATINUM PT QS','categoria'=>'COLCHONES','marca'=>'SIMMONS','descripcion'=>'CAMA CAJONES SIMMONS BEAUTYREST PLATINUM PT QS','precio'=>'7249','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'1000000000','sku'=>'16905232','cadena_id'=>'8','nombre'=>'CAMA CAJONES SIMMONS BEAUTYREST PLATINUM PT KING','categoria'=>'COLCHONES','marca'=>'SIMMONS','descripcion'=>'CAMA CAJONES SIMMONS BEAUTYREST PLATINUM PT KING','precio'=>'8949','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'1346001501          ','sku'=>'16905177','cadena_id'=>'8','nombre'=>'CAM PRACTIBOX GRIS  BEAUTYREST SILVER PT 2 PLZ','categoria'=>'COLCHONES','marca'=>'SIMMONS','descripcion'=>'CAM PRACTIBOX GRIS  BEAUTYREST SILVER PT 2 PLZ','precio'=>'4149','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'1347001501          ','sku'=>'16905178','cadena_id'=>'8','nombre'=>'CAM PRACTIBOX GRIS  BEAUTYREST SILVER PT QUEEN','categoria'=>'COLCHONES','marca'=>'SIMMONS','descripcion'=>'CAM PRACTIBOX GRIS  BEAUTYREST SILVER PT QUEEN','precio'=>'4999','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'1115040502          ','sku'=>'16905179','cadena_id'=>'8','nombre'=>'CAMA CAJONES BEAUTYREST SILVER PT 2 PL','categoria'=>'COLCHONES','marca'=>'SIMMONS','descripcion'=>'CAMA CAJONES BEAUTYREST SILVER PT 2 PL','precio'=>'4149','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'1116040502          ','sku'=>'16905180','cadena_id'=>'8','nombre'=>'CAMA CAJONES BEAUTYREST SILVER PT QS','categoria'=>'COLCHONES','marca'=>'SIMMONS','descripcion'=>'CAMA CAJONES BEAUTYREST SILVER PT QS','precio'=>'4999','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'1117040502          ','sku'=>'16905181','cadena_id'=>'8','nombre'=>'CAMA CAJONES BEAUTYREST SILVER PT KING','categoria'=>'COLCHONES','marca'=>'SIMMONS','descripcion'=>'CAMA CAJONES BEAUTYREST SILVER PT KING','precio'=>'6149','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'1346001501','sku'=>'1522444','cadena_id'=>'3','nombre'=>'CAMA PRAKTIBOX GRIS SIMMONS SILVER PT QUEEN','categoria'=>'COLCHONES','marca'=>'SIMMONS','descripcion'=>'CAMA PRAKTIBOX GRIS SIMMONS SILVER PT QUEEN','precio'=>'4149','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'1347001501','sku'=>'1522406','cadena_id'=>'3','nombre'=>'CAMA PRAKTIBOX GRIS SIMMONS SILVER PT 2 PLAZAS','categoria'=>'COLCHONES','marca'=>'SIMMONS','descripcion'=>'CAMA PRAKTIBOX GRIS SIMMONS SILVER PT 2 PLAZAS','precio'=>'4999','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'1115040502','sku'=>'1522447','cadena_id'=>'3','nombre'=>'CAMA AMERICANA SIMMONS BEAUTYREST CANTABRIA SILVER PT 2 PLAZAS','categoria'=>'COLCHONES','marca'=>'SIMMONS','descripcion'=>'CAMA AMERICANA SIMMONS BEAUTYREST CANTABRIA SILVER PT 2 PLAZAS','precio'=>'4149','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'1116040502','sku'=>'1522480','cadena_id'=>'3','nombre'=>'CAMA AMERICANA SIMMONS BEAUTYREST CANTABRIA SILVER PT QUEEN','categoria'=>'COLCHONES','marca'=>'SIMMONS','descripcion'=>'CAMA AMERICANA SIMMONS BEAUTYREST CANTABRIA SILVER PT QUEEN','precio'=>'4999','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'1117040502','sku'=>'1522352','cadena_id'=>'3','nombre'=>'CAMA AMERICANA SIMMONS BEAUTYREST CANTABRIA SILVER PT KING','categoria'=>'COLCHONES','marca'=>'SIMMONS','descripcion'=>'CAMA AMERICANA SIMMONS BEAUTYREST CANTABRIA SILVER PT KING','precio'=>'6149','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'1000000000','sku'=>'1522460','cadena_id'=>'3','nombre'=>'CAMA PRACTIBOX GRIS RECHARGE P/T 2 PLZ','categoria'=>'COLCHONES','marca'=>'SIMMONS','descripcion'=>'CAMA PRACTIBOX GRIS RECHARGE P/T 2 PLZ','precio'=>'4149','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'1000000000','sku'=>'1522373','cadena_id'=>'3','nombre'=>'CAMA BASE CAJONES NEGRA RECHARGE PT 2PLZ','categoria'=>'COLCHONES','marca'=>'SIMMONS','descripcion'=>'CAMA BASE CAJONES NEGRA RECHARGE PT 2PLZ','precio'=>'4149','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'1000000000','sku'=>'1522442','cadena_id'=>'3','nombre'=>'CAM BASE CAJONES NEGRA RECHARGE PT QUEEN','categoria'=>'COLCHONES','marca'=>'SIMMONS','descripcion'=>'CAM BASE CAJONES NEGRA RECHARGE PT QUEEN','precio'=>'4999','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'1000000000','sku'=>'1522394','cadena_id'=>'3','nombre'=>'CAMA BASE CAJONES NEGRA RECHARGE PT KING','categoria'=>'COLCHONES','marca'=>'SIMMONS','descripcion'=>'CAMA BASE CAJONES NEGRA RECHARGE PT KING','precio'=>'6149','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'1000000000','sku'=>'1522417','cadena_id'=>'3','nombre'=>'CAMA PRACTIBOX GRIS PLATINUM P/T 2 PLZ','categoria'=>'COLCHONES','marca'=>'SIMMONS','descripcion'=>'CAMA PRACTIBOX GRIS PLATINUM P/T 2 PLZ','precio'=>'6549','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'1000000000','sku'=>'1522475','cadena_id'=>'3','nombre'=>'CAMA PRACTIBOX GRIS PLATINUM P/T QUEEN','categoria'=>'COLCHONES','marca'=>'SIMMONS','descripcion'=>'CAMA PRACTIBOX GRIS PLATINUM P/T QUEEN','precio'=>'7249','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'1000000000','sku'=>'1522429','cadena_id'=>'3','nombre'=>'CAMA BASE CAJONES NEGRA PLATINUM PT 2PLZ','categoria'=>'COLCHONES','marca'=>'SIMMONS','descripcion'=>'CAMA BASE CAJONES NEGRA PLATINUM PT 2PLZ','precio'=>'6549','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'1000000000','sku'=>'1522369','cadena_id'=>'3','nombre'=>'CAM BASE CAJONES NEGRA PLATINUM PT QUEEN','categoria'=>'COLCHONES','marca'=>'SIMMONS','descripcion'=>'CAM BASE CAJONES NEGRA PLATINUM PT QUEEN','precio'=>'7249','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'1000000000','sku'=>'1522396','cadena_id'=>'3','nombre'=>'CAMA BASE CAJONES NEGRA PLATINUM PT KING','categoria'=>'COLCHONES','marca'=>'SIMMONS','descripcion'=>'CAMA BASE CAJONES NEGRA PLATINUM PT KING','precio'=>'8949','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'1115050402','sku'=>'21694508','cadena_id'=>'7','nombre'=>'CAMA CAJONES PERFECTSLEEPER KLEINMON 2P','categoria'=>'COLCHONES','marca'=>'SERTA','descripcion'=>'CAMA CAJONES PERFECTSLEEPER KLEINMON 2P','precio'=>'5550','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'1116050402','sku'=>'21694509','cadena_id'=>'7','nombre'=>'CAMA CAJONES P.SLEEPER KLEINMON QUEEN','categoria'=>'COLCHONES','marca'=>'SERTA','descripcion'=>'CAMA CAJONES P.SLEEPER KLEINMON QUEEN','precio'=>'6143.22','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'1117050402','sku'=>'21694510','cadena_id'=>'7','nombre'=>'CAMA CAJONES P.SLEEPER KLEINMON KING','categoria'=>'COLCHONES','marca'=>'SERTA','descripcion'=>'CAMA CAJONES P.SLEEPER KLEINMON KING','precio'=>'7583.9','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'1115050302','sku'=>'21694511','cadena_id'=>'7','nombre'=>'CAMA  CAJONES WESBOUROUGH PT 2 P','categoria'=>'COLCHONES','marca'=>'SERTA','descripcion'=>'CAMA  CAJONES WESBOUROUGH PT 2 P','precio'=>'3516.1','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'1116050302','sku'=>'21694512','cadena_id'=>'7','nombre'=>'CAMA CAJONES WESBOUROUGH PT QUEEN','categoria'=>'COLCHONES','marca'=>'SERTA','descripcion'=>'CAMA CAJONES WESBOUROUGH PT QUEEN','precio'=>'4236.44','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'1117050302','sku'=>'21694513','cadena_id'=>'7','nombre'=>'CAMA CAJONES WESBOUROUGH PT KING','categoria'=>'COLCHONES','marca'=>'SERTA','descripcion'=>'CAMA CAJONES WESBOUROUGH PT KING','precio'=>'5295.76','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'1115050202','sku'=>'21694514','cadena_id'=>'7','nombre'=>'CAMA CAJONES SERTAPEDIC WAITROSE 2 P','categoria'=>'COLCHONES','marca'=>'SERTA','descripcion'=>'CAMA CAJONES SERTAPEDIC WAITROSE 2 P','precio'=>'2626.27','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'1116050202','sku'=>'21694515','cadena_id'=>'7','nombre'=>'CAMA CAJONES SERTAPEDIC WAITROSE QUEEN','categoria'=>'COLCHONES','marca'=>'SERTA','descripcion'=>'CAMA CAJONES SERTAPEDIC WAITROSE QUEEN','precio'=>'3219.49','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'1117050202','sku'=>'21694516','cadena_id'=>'7','nombre'=>'CAMA CAJONES SERTAPEDIC WAITROSE KING','categoria'=>'COLCHONES','marca'=>'SERTA','descripcion'=>'CAMA CAJONES SERTAPEDIC WAITROSE KING','precio'=>'4066.95','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'1000000000','sku'=>'21694517','cadena_id'=>'7','nombre'=>'CAMA P.BOX GRIS P.SLEEPER KLEIN PT 2PZ','categoria'=>'COLCHONES','marca'=>'SERTA','descripcion'=>'CAMA P.BOX GRIS P.SLEEPER KLEIN PT 2PZ','precio'=>'5550','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'1000000000','sku'=>'21694518','cadena_id'=>'7','nombre'=>'CAMA P.BOX GRIS P.SLEEPER KLEIN PT QUEEN','categoria'=>'COLCHONES','marca'=>'SERTA','descripcion'=>'CAMA P.BOX GRIS P.SLEEPER KLEIN PT QUEEN','precio'=>'6143.22','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'1000000000','sku'=>'21694519','cadena_id'=>'7','nombre'=>'CAMA P.BOX GRIS  WESBOUROUGH PT 2 PZ','categoria'=>'COLCHONES','marca'=>'SERTA','descripcion'=>'CAMA P.BOX GRIS  WESBOUROUGH PT 2 PZ','precio'=>'3516.1','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'1000000000','sku'=>'21694520','cadena_id'=>'7','nombre'=>'CAMA P.BOX GRIS  WESBOUROUGH PT QUEEN','categoria'=>'COLCHONES','marca'=>'SERTA','descripcion'=>'CAMA P.BOX GRIS  WESBOUROUGH PT QUEEN','precio'=>'4236.44','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'1345001201','sku'=>'21694521','cadena_id'=>'7','nombre'=>'CAMA P.BOX GRIS SERTAPEDIC WAITROSE 2 PZ','categoria'=>'COLCHONES','marca'=>'SERTA','descripcion'=>'CAMA P.BOX GRIS SERTAPEDIC WAITROSE 2 PZ','precio'=>'2626.27','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'1346001201','sku'=>'21694522','cadena_id'=>'7','nombre'=>'CAMA P.BOX GRIS SERTAPEDIC WAITROSE QUEEN','categoria'=>'COLCHONES','marca'=>'SERTA','descripcion'=>'CAMA P.BOX GRIS SERTAPEDIC WAITROSE QUEEN','precio'=>'3219.49','UNIDAD'=>'SET']);
      Producto::create(['sku_cic'=>'2141020601','sku'=>'2141020601','cadena_id'=>'1','nombre'=>'COLCHON LATEX PRO CUNA','categoria'=>'COLCHONES','marca'=>'DRIMER','descripcion'=>'COLCHON LATEX PRO CUNA','precio'=>'1500','UNIDAD'=>'UND']);
      Producto::create(['sku_cic'=>'2137020101','sku'=>'2137020101','cadena_id'=>'1','nombre'=>'COLCHON ESPUMA C500 ANTIESTRESS KING 7"','categoria'=>'COLCHONES','marca'=>'DRIMER','descripcion'=>'COLCHON ESPUMA C500 ANTIESTRESS KING 7"','precio'=>'1500','UNIDAD'=>'UND']);
      Producto::create(['sku_cic'=>'6190000001','sku'=>'6190000001','cadena_id'=>'1','nombre'=>'FLETE Y TRANSPORTE Y VARIOS','categoria'=>'COLCHONES','marca'=>'CONTINENTAL','descripcion'=>'FLETE Y TRANSPORTE Y VARIOS','precio'=>'1','UNIDAD'=>'UND']);
      Producto::create(['sku_cic'=>'2561020703','sku'=>'2561020703','cadena_id'=>'1','nombre'=>'PROTECTOR COLCHON AMOLDABLE 100% POLIESTER IMPERMEABLE CUNA','categoria'=>'ROPA DE CAMA','marca'=>'DRIMER','descripcion'=>'PROTECTOR COLCHON AMOLDABLE 100% POLIESTER IMPERMEABLE CUNA','precio'=>'100','UNIDAD'=>'UND']);
      Producto::create(['sku_cic'=>'2562020703','sku'=>'2562020703','cadena_id'=>'1','nombre'=>'PROTECTOR COLCHON AMOLDABLE 100% POLIESTER IMPERMEABLE 1 PLAZA','categoria'=>'ROPA DE CAMA','marca'=>'DRIMER','descripcion'=>'PROTECTOR COLCHON AMOLDABLE 100% POLIESTER IMPERMEABLE 1 PLAZA','precio'=>'100','UNIDAD'=>'UND']);
      Producto::create(['sku_cic'=>'2564020703','sku'=>'2564020703','cadena_id'=>'1','nombre'=>'PROTECTOR COLCHON AMOLDABLE 100% POLIESTER IMPERMEABLE 1.5 PLAZAS','categoria'=>'ROPA DE CAMA','marca'=>'DRIMER','descripcion'=>'PROTECTOR COLCHON AMOLDABLE 100% POLIESTER IMPERMEABLE 1.5 PLAZAS','precio'=>'100','UNIDAD'=>'UND']);
      Producto::create(['sku_cic'=>'2565020703','sku'=>'2565020703','cadena_id'=>'1','nombre'=>'PROTECTOR COLCHON AMOLDABLE 100% POLIESTER IMPERMEABLE 2 PLAZAS','categoria'=>'ROPA DE CAMA','marca'=>'DRIMER','descripcion'=>'PROTECTOR COLCHON AMOLDABLE 100% POLIESTER IMPERMEABLE 2 PLAZAS','precio'=>'100','UNIDAD'=>'UND']);
      Producto::create(['sku_cic'=>'2566020703','sku'=>'2566020703','cadena_id'=>'1','nombre'=>'PROTECTOR COLCHON AMOLDABLE 100% POLIESTER IMPERMEABLE QUEEN','categoria'=>'ROPA DE CAMA','marca'=>'DRIMER','descripcion'=>'PROTECTOR COLCHON AMOLDABLE 100% POLIESTER IMPERMEABLE QUEEN','precio'=>'100','UNIDAD'=>'UND']);
      Producto::create(['sku_cic'=>'2567020703','sku'=>'2567020703','cadena_id'=>'1','nombre'=>'PROTECTOR COLCHON AMOLDABLE 100% POLIESTER IMPERMEABLE KING','categoria'=>'ROPA DE CAMA','marca'=>'DRIMER','descripcion'=>'PROTECTOR COLCHON AMOLDABLE 100% POLIESTER IMPERMEABLE KING','precio'=>'100','UNIDAD'=>'UND']);
      Producto::create(['sku_cic'=>'2564050501','sku'=>'2564050501','cadena_id'=>'1','nombre'=>'PROTECTOR COLCHON IMPERMEABLE 100% POLIESTER SERTA 1.5 PLAZA','categoria'=>'ROPA DE CAMA','marca'=>'SERTA','descripcion'=>'PROTECTOR COLCHON IMPERMEABLE 100% POLIESTER SERTA 1.5 PLAZA','precio'=>'100','UNIDAD'=>'UND']);
      Producto::create(['sku_cic'=>'2565050501','sku'=>'2565050501','cadena_id'=>'1','nombre'=>'PROTECTOR COLCHON IMPERMEABLE 100% POLIESTER SERTA 2 PLAZAS','categoria'=>'ROPA DE CAMA','marca'=>'SERTA','descripcion'=>'PROTECTOR COLCHON IMPERMEABLE 100% POLIESTER SERTA 2 PLAZAS','precio'=>'100','UNIDAD'=>'UND']);
      Producto::create(['sku_cic'=>'2566050501','sku'=>'2566050501','cadena_id'=>'1','nombre'=>'PROTECTOR COLCHON IMPERMEABLE 100% POLIESTER SERTA QUEEN','categoria'=>'ROPA DE CAMA','marca'=>'SERTA','descripcion'=>'PROTECTOR COLCHON IMPERMEABLE 100% POLIESTER SERTA QUEEN','precio'=>'100','UNIDAD'=>'UND']);
      Producto::create(['sku_cic'=>'2567050501','sku'=>'2567050501','cadena_id'=>'1','nombre'=>'PROTECTOR COLCHON IMPERMEABLE 100% POLIESTER SERTA KING','categoria'=>'ROPA DE CAMA','marca'=>'SERTA','descripcion'=>'PROTECTOR COLCHON IMPERMEABLE 100% POLIESTER SERTA KING','precio'=>'100','UNIDAD'=>'UND']);

    }
}
